(function(g){var window=this;var $Ga=function(a,b){return g.Mb(a,b)},k4=function(a,b,c){a.C.set(b,c)},l4=function(a){k4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.B()).toString(36));
return a},m4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.hn(a.C,b,c)},aHa=function(a,b){var c=[];
g.mj(b,function(d){try{var e=g.eo.prototype.B.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.co(e)&&c.push(d)},a);
return c},bHa=function(a,b){var c=aHa(a,b);
g.Ab(c,function(d){g.eo.prototype.remove.call(this,d)},a)},cHa=function(a){if(a.U){if(a.U.locationOverrideToken)return{locationOverrideToken:a.U.locationOverrideToken};
if(null!=a.U.latitudeE7&&null!=a.U.longitudeE7)return{latitudeE7:a.U.latitudeE7,longitudeE7:a.U.longitudeE7}}return null},dHa=function(a,b){g.fb(a,b)||a.push(b)},n4=function(a){var b=0,c;
for(c in a)b++;return b},eHa=function(a,b){var c=b instanceof g.Bc?b:g.Hc(b,/^data:image\//i.test(b));
a.src=g.Cc(c)},o4=function(){},fHa=function(a){try{return g.z.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gHa=function(a){if(a.Zf&&"function"==typeof a.Zf)return a.Zf();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Jb(a)},hHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)g.Ab(a,b,void 0);else{if(a.yh&&"function"==typeof a.yh)var c=a.yh();else if(a.Zf&&"function"==typeof a.Zf)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=gHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},iHa=function(a,b,c,d){var e=new g.Wm(null,void 0);
a&&g.Xm(e,a);b&&g.Ym(e,b);c&&g.Zm(e,c);d&&(e.B=d);return e},p4=function(a,b){g.No[a]=!0;
var c=g.Lo();c&&c.publish.apply(c,arguments);g.No[a]=!1},q4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Tm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",jHa(this,a.capabilities||""),kHa(this,a.experiments||""))},jHa=function(a,b){a.capabilities.clear();
g.Me(b.split(","),g.Pa($Ga,lHa)).forEach(function(c){a.capabilities.add(c)})},kHa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},r4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},s4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},mHa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},nHa=function(a){return new r4(a)},oHa=function(a){return Array.isArray(a)?g.Lc(a,nHa):[]},t4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},u4=function(a){return Array.isArray(a)?"["+g.Lc(a,t4).join(",")+"]":"null"},v4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},pHa=function(a){return g.Lc(a,function(b){return{key:b.id,
name:b.name}})},w4=function(a,b){return g.bb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},x4=function(a,b){return g.bb(a,function(c){return s4(c,b)})},qHa=function(){var a=(0,g.Bu)();
a&&bHa(a,a.u.bk(!0))},y4=function(){var a=g.Eu("yt-remote-connected-devices")||[];
g.xb(a);return a},rHa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Lc(a,function(d,e){return 0==e?d:d.substring(c.length)})},sHa=function(a){g.Du("yt-remote-connected-devices",a,86400)},A4=function(){if(z4)return z4;
var a=g.Eu("yt-remote-device-id");a||(a=v4(),g.Du("yt-remote-device-id",a,31536E3));for(var b=y4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return z4=d},B4=function(){var a=y4(),b=A4();
g.fb(a,b);g.Gu()&&g.zb(a,b);a=rHa(a);if(g.gb(a))try{g.Fq("remote_sid")}catch(c){}else try{g.Dq("remote_sid",a.join(","),-1)}catch(c){}},tHa=function(){return g.Eu("yt-remote-session-browser-channel")},uHa=function(){return g.Eu("yt-remote-local-screens")||[]},vHa=function(){g.Du("yt-remote-lounge-token-expiration",!0,86400)},wHa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Lc(uHa(),function(d){return d.loungeToken}),c=g.Lc(a,function(d){return d.loungeToken});
g.th(c,function(d){return!g.fb(b,d)})&&vHa();
g.Du("yt-remote-local-screens",a,31536E3)},xHa=function(a,b){g.Du("yt-remote-session-browser-channel",a);
g.Du("yt-remote-session-screen-id",b);var c=y4(),d=A4();g.fb(c,d)||c.push(d);sHa(c);B4()},C4=function(a){a||(g.Fu("yt-remote-session-screen-id"),g.Fu("yt-remote-session-video-id"));
B4();a=y4();g.kb(a,A4());sHa(a)},yHa=function(){if(!D4){var a=g.oo();
a&&(D4=new g.Yn(a))}},zHa=function(){yHa();
return D4?!!D4.get("yt-remote-use-staging-server"):!1},AHa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},BHa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},E4=function(a){a.length?CHa(a.shift(),function(){E4(a)}):F4()},DHa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},CHa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.gd(d,g.ug(a));(document.head||document.documentElement).appendChild(d)},F4=function(){var a=BHa();
a&&a(!1,"No cast extension found")},FHa=function(){if(EHa){var a=2,b=BHa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;CHa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",F4,c)}},GHa=function(){FHa();
var a=(a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/))?parseInt(a[1],10):0;var b=[];if(0!=a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}b.push("//www.gstatic.com/eureka/clank/cast_sender.js");E4(b)},G4=function(a,b,c){g.C.call(this);
this.I=null!=c?(0,g.A)(a,c):a;this.Lf=b;this.F=(0,g.A)(this.hK,this);this.u=!1;this.B=0;this.C=this.gb=null;this.D=[]},H4=function(a,b,c){g.C.call(this);
this.D=null!=c?a.bind(c):a;this.Lf=b;this.C=null;this.u=!1;this.B=0;this.gb=null},I4=function(a){a.gb=g.Rm(function(){a.gb=null;
a.u&&!a.B&&(a.u=!1,I4(a))},a.Lf);
var b=a.C;a.C=null;a.D.apply(null,b)},J4=function(a){if(g.z.JSON)try{return g.z.JSON.parse(a)}catch(b){}return fHa(a)},K4=function(){},L4=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.z.setTimeout(function(){a()},b)},N4=function(a){M4.dispatchEvent(new HHa(M4,a))},HHa=function(a){g.Kl.call(this,"statevent",a)},O4=function(){},IHa=function(){},KHa=function(a){return(a=JHa(a))?new ActiveXObject(a):new XMLHttpRequest},JHa=function(a){if(!a.B&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.B=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.B},P4=function(a,b,c,d){this.u=a;
this.B=b;this.N=c;this.K=d||1;this.F=45E3;this.D=new g.p_(this);this.C=new g.Qm;this.C.setInterval(250)},MHa=function(a,b,c){a.Zp=1;
a.ol=l4(b.clone());a.Nn=c;a.I=!0;LHa(a,null)},Q4=function(a,b,c,d,e){a.Zp=1;
a.ol=l4(b.clone());a.Nn=null;a.I=c;e&&(a.jH=!1);LHa(a,d)},LHa=function(a,b){a.Pp=g.B();
R4(a);a.im=a.ol.clone();m4(a.im,"t",a.K);a.Ys=0;a.De=a.u.Wx(a.u.Gs()?b:null);0<a.Uw&&(a.vv=new H4((0,g.A)(a.eI,a,a.De),a.Uw));a.D.ya(a.De,"readystatechange",a.OQ);var c=a.Em?g.Tb(a.Em):{};a.Nn?(a.ew="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.De.send(a.im,a.ew,a.Nn,c)):(a.ew="GET",a.jH&&!g.Ae&&(c.Connection="close"),a.De.send(a.im,a.ew,null,c));a.u.mi(1)},PHa=function(a,b,c){for(var d=!0;!a.Ym&&a.Ys<c.length;){var e=NHa(a,c);
if(e==S4){4==b&&(a.fl=4,N4(15),d=!1);break}else if(e==OHa){a.fl=4;N4(16);d=!1;break}else T4(a,e)}4==b&&0==c.length&&(a.fl=1,N4(17),d=!1);a.Di=a.Di&&d;d||(U4(a),V4(a))},NHa=function(a,b){var c=a.Ys,d=b.indexOf("\n",c);
if(-1==d)return S4;c=Number(b.substring(c,d));if(isNaN(c))return OHa;d+=1;if(d+c>b.length)return S4;var e=b.substr(d,c);a.Ys=d+c;return e},RHa=function(a,b){a.Pp=g.B();
R4(a);var c=b?window.location.hostname:"";a.im=a.ol.clone();k4(a.im,"DOMAIN",c);k4(a.im,"t",a.K);try{a.Hi=new ActiveXObject("htmlfile")}catch(n){U4(a);a.fl=7;N4(22);V4(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in W4)h=W4[h];else if(h in QHa)h=W4[h]=QHa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
W4[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.dd(g.dc("b/12014412"),d+"</body></html>");a.Hi.open();a.Hi.write(g.$c(c));a.Hi.close();a.Hi.parentWindow.m=(0,g.A)(a.gQ,a);a.Hi.parentWindow.d=(0,g.A)(a.tG,a,!0);a.Hi.parentWindow.rpcClose=(0,g.A)(a.tG,a,!1);c=a.Hi.createElement("DIV");a.Hi.parentWindow.document.body.appendChild(c);d=g.Gc(a.im.toString());d=g.ld(g.Cc(d));d=g.dd(g.dc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ed(c,d);a.u.mi(1)},R4=function(a){a.YA=g.B()+a.F;
SHa(a,a.F)},SHa=function(a,b){if(null!=a.gq)throw Error("WatchDog timer not null");
a.gq=L4((0,g.A)(a.oQ,a),b)},X4=function(a){a.gq&&(g.z.clearTimeout(a.gq),a.gq=null)},V4=function(a){a.u.ZB()||a.Ym||a.u.wt(a)},U4=function(a){X4(a);
g.ag(a.vv);a.vv=null;a.C.stop();g.rBa(a.D);if(a.De){var b=a.De;a.De=null;b.abort();b.dispose()}a.Hi&&(a.Hi=null)},T4=function(a,b){try{a.u.kG(a,b),a.u.mi(4)}catch(c){}},UHa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;THa(a,b,function(h){h?c(!0):g.z.setTimeout(function(){UHa(a,b,c,d,f)},f)})}},THa=function(a,b,c){var d=new Image;
d.onload=function(){try{Y4(d),c(!0)}catch(e){}};
d.onerror=function(){try{Y4(d),c(!1)}catch(e){}};
d.onabort=function(){try{Y4(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{Y4(d),c(!1)}catch(e){}};
g.z.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
eHa(d,a)},Y4=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Z4=function(a){g.gm.call(this);
this.headers=new g.Tm;this.da=a||null;this.D=!1;this.Z=this.u=null;this.xa=this.U="";this.I=0;this.C="";this.F=this.ka=this.N=this.ea=!1;this.K=0;this.W=null;this.Aa="";this.X=this.ga=!1},VHa=function(a){return g.ye&&g.be(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},WHa=function(a){return"content-type"==a.toLowerCase()},YHa=function(a,b){a.D=!1;
a.u&&(a.F=!0,a.u.abort(),a.F=!1);a.C=b;a.I=5;XHa(a);$4(a)},XHa=function(a){a.ea||(a.ea=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},$Ha=function(a){if(a.D&&"undefined"!=typeof g.u_)if(a.Z[1]&&4==a5(a)&&2==a.getStatus())b5(a,"Local request error detected and ignored");
else if(a.N&&4==a5(a))g.Rm(a.hG,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){b5(a,"Request complete");a.D=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.ud(1,String(a.U));if(!f&&g.z.self&&g.z.self.location){var h=g.z.self.location.protocol;f=h.substr(0,h.length-1)}e=!ZHa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<a5(a)?a.u.statusText:""}catch(m){l=""}a.C=l+" ["+a.getStatus()+"]";XHa(a)}}finally{$4(a)}}},$4=function(a,b){if(a.u){aIa(a);
var c=a.u,d=a.Z[0]?g.Ia:null;a.u=null;a.Z=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},aIa=function(a){a.u&&a.X&&(a.u.ontimeout=null);
a.W&&(g.z.clearTimeout(a.W),a.W=null)},a5=function(a){return a.u?a.u.readyState:0},c5=function(a){try{return a.u?a.u.responseText:""}catch(b){return""}},b5=function(a,b){return b+" ["+a.xa+" "+a.U+" "+a.getStatus()+"]"},bIa=function(a){this.u=a;
this.B=new K4},cIa=function(a){var b=d5(a.u,a.Iq,"/mail/images/cleardot.gif");
l4(b);UHa(b.toString(),5E3,(0,g.A)(a.cL,a),3,2E3);a.mi(1)},f5=function(a){var b=a.u.N;
if(null!=b)N4(5),b?(N4(11),e5(a.u,a,!1)):(N4(12),e5(a.u,a,!0));else if(a.Fg=new P4(a,void 0,void 0,void 0),a.Fg.Em=a.Vw,b=a.u,b=d5(b,b.Gs()?a.zq:null,a.Ww),N4(5),!g.ye||g.ce(10))m4(b,"TYPE","xmlhttp"),Q4(a.Fg,b,!1,a.zq,!1);else{m4(b,"TYPE","html");var c=a.Fg;a=!!a.zq;c.Zp=3;c.ol=l4(b.clone());RHa(c,a)}},g5=function(a,b,c){this.La=1;
this.u=[];this.C=[];this.D=new K4;this.K=a||null;this.N=null!=b?b:null;this.F=c||!1},dIa=function(a,b){this.u=a;
this.map=b;this.context=null},eIa=function(a,b,c,d){g.Kl.call(this,"timingevent",a);
this.size=b;this.ys=d},fIa=function(a){g.Kl.call(this,"serverreachability",a)},iIa=function(a){gIa(a);
if(3==a.La){var b=a.Ur++,c=a.Ut.clone();k4(c,"SID",a.B);k4(c,"RID",b);k4(c,"TYPE","terminate");h5(a,c);b=new P4(a,a.B,b,void 0);b.Zp=2;b.ol=l4(c.clone());eHa(new Image,b.ol.toString());b.Pp=g.B();R4(b)}hIa(a)},jIa=function(a){a.xL(1,0);
a.Ut=d5(a,null,a.Xw);i5(a)},gIa=function(a){a.sl&&(a.sl.abort(),a.sl=null);
a.ae&&(a.ae.cancel(),a.ae=null);a.ck&&(g.z.clearTimeout(a.ck),a.ck=null);j5(a);a.sg&&(a.sg.cancel(),a.sg=null);a.Al&&(g.z.clearTimeout(a.Al),a.Al=null)},kIa=function(a,b){if(0==a.La)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new dIa(a.eN++,b));2!=a.La&&3!=a.La||i5(a)},lIa=function(a){var b=0;
a.ae&&b++;a.sg&&b++;return b},i5=function(a){a.sg||a.Al||(a.Al=L4((0,g.A)(a.rG,a),0),a.So=0)},nIa=function(a,b){if(1==a.La){if(!b){a.Ur=Math.floor(1E5*Math.random());
var c=a.Ur++,d=new P4(a,"",c,void 0);d.Em=a.Pi;var e=k5(a),f=a.Ut.clone();k4(f,"RID",c);k4(f,"CVER","1");h5(a,f);MHa(d,f,e);a.sg=d;a.La=2}}else 3==a.La&&(b?mIa(a,b):0==a.u.length||a.sg||mIa(a))},mIa=function(a,b){if(b)if(6<a.Zm){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Ur-1;var d=k5(a)}else c=b.N,d=b.Nn;else c=a.Ur++,d=k5(a);var e=a.Ut.clone();k4(e,"SID",a.B);k4(e,"RID",c);k4(e,"AID",a.pp);h5(a,e);c=new P4(a,a.B,c,a.So+1);c.Em=a.Pi;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.sg=c;MHa(c,e,d)},h5=function(a,b){if(a.Cf){var c=a.Cf.ND();
c&&g.Cb(c,function(d,e){k4(b,e,d)})}},k5=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Zm&&0<b){var d=a.u[0].u;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={ko:e.ko},f++){e.ko=a.u[f].u;var h=a.u[f].map;e.ko=6>=a.Zm?f:e.ko-d;try{g.Cb(h,function(l){return function(m,n){c.push("req"+l.ko+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.ko+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},oIa=function(a){a.ae||a.ck||(a.I=1,a.ck=L4((0,g.A)(a.qG,a),0),a.Do=0)},l5=function(a){if(a.ae||a.ck||3<=a.Do)return!1;
a.I++;a.ck=L4((0,g.A)(a.qG,a),pIa(a,a.Do));a.Do++;return!0},e5=function(a,b,c){a.bw=c;
a.Qi=b.Zj;a.F||jIa(a)},j5=function(a){null!=a.gn&&(g.z.clearTimeout(a.gn),a.gn=null)},pIa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},m5=function(a,b){if(2==b||9==b){var c=null;
a.Cf&&(c=null);var d=(0,g.A)(a.xR,a);c||(c=new g.Wm("//www.google.com/images/cleardot.gif"),l4(c));THa(c.toString(),1E4,d)}else N4(2);qIa(a,b)},qIa=function(a,b){a.La=0;
a.Cf&&a.Cf.cD(b);hIa(a);gIa(a)},hIa=function(a){a.La=0;
a.Qi=-1;if(a.Cf)if(0==a.C.length&&0==a.u.length)a.Cf.Jx();else{g.ob(a.C);var b=g.ob(a.u);a.C.length=0;a.u.length=0;a.Cf.Jx(b)}},d5=function(a,b,c){var d=g.dn(c);
if(""!=d.u)b&&g.Ym(d,b+"."+d.u),g.Zm(d,d.D);else{var e=window.location;d=iHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.er&&g.Cb(a.er,function(f,h){k4(d,h,f)});
k4(d,"VER",a.Zm);h5(a,d);return d},rIa=function(){},sIa=function(){this.u=[];
this.B=[]},tIa=function(a,b){this.action=a;
this.params=b||{}},n5=function(a,b){g.C.call(this);
this.u=new g.J(this.YP,0,this);g.E(this,this.u);this.Lf=5E3;this.B=0;if("function"===typeof a)b&&(a=(0,g.A)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},o5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.Z=a;this.I=b;this.C=new g.Qn;this.B=new n5(this.ZQ,this);this.u=null;this.W=!1;this.F=null;this.U="";this.N=this.D=0;this.K=[];this.da=c;this.X=d;this.ga=e},uIa=function(a){return{firstTestResults:[""],
secondTestResults:!a.u.bw,sessionId:a.u.B,arrayId:a.u.pp}},vIa=function(a,b){a.N=b||0;
a.B.stop();p5(a);a.u&&(3==a.u.getState()&&nIa(a.u),iIa(a.u));a.N=0},q5=function(a){return!!a.u&&3==a.u.getState()},p5=function(a){if(a.u){var b=a.X(),c=a.u.Pi||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.u.Pi=c}},r5=function(a){this.scheme="https";
this.port=this.domain="";this.u="/api/lounge";this.B=!0;a=a||document.location.href;var b=Number(g.ud(4,a))||"";b&&(this.port=":"+b);this.domain=g.vd(a)||"";a=g.Tc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zc(a,"10.0")&&(this.B=!1))},s5=function(a,b){var c=a.u;
a.B&&(c=a.scheme+"://"+a.domain+a.port+a.u);return g.Kd(c+b,{})},t5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.D,d,!0),onError:g.Pa(a.C,e),onTimeout:g.Pa(a.F,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.xq(b,a)},zIa=function(){var a=wIa;
xIa();u5.push(a);yIa()},v5=function(a,b){xIa();
var c=AIa(a,String(b));g.gb(u5)?BIa(c):(yIa(),g.Ab(u5,function(d){d(c)}))},xIa=function(){u5||(u5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Da("yt.mdx.remote.debug.handlers_",u5,void 0))},BIa=function(a){var b=(w5+1)%50;
w5=b;x5[b]=a;y5||(y5=49==b)},yIa=function(){var a=u5;
if(x5[0]){var b=y5?w5:-1;do{b=(b+1)%50;var c=x5[b];g.Ab(a,function(d){d(c)})}while(b!=w5);
x5=Array(50);w5=-1;y5=!1}},AIa=function(a,b){var c=(g.B()-CIa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},z5=function(a){g.O.call(this);
this.I=a;this.screens=[]},DIa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},EIa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Me(a.screens,function(f){return!!w4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=DIa(a,b[d])||c;return c},FIa=function(a,b){var c=a.screens.length;
a.screens=g.Me(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},A5=function(a,b,c,d){g.O.call(this);
this.C=a;this.I=b;this.D=c;this.F=d;this.B=0;this.u=null;this.gb=NaN},C5=function(a){z5.call(this,"LocalScreenService");
this.B=a;this.u=NaN;B5(this);this.info("Initializing with "+u4(this.screens))},GIa=function(a){if(a.screens.length){var b=g.Lc(a.screens,function(d){return d.id}),c=s5(a.B,"/pairing/get_lounge_token_batch");
t5(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.eM,a),(0,g.A)(a.dM,a))}},B5=function(a){if(g.Yo("deprecate_pair_servlet_enabled"))return EIa(a,[]);
var b=oHa(uHa());b=g.Me(b,function(c){return!c.uuid});
return EIa(a,b)},D5=function(a,b){wHa(g.Lc(a.screens,mHa));
b&&vHa()},F5=function(a,b){g.O.call(this);
this.I=b;var c=g.Eu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.u=d;this.F=a;this.C=this.D=NaN;this.B=null;E5("Initialized with "+g.Sj(this.u))},G5=function(a,b,c){var d=s5(a.F,"/pairing/get_screen_availability");
t5(a.F,d,{lounge_token:b.token},(0,g.A)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},H5=function(a,b){a:if(n4(b)!=n4(a.u))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.u[c[d]]){c=!1;break a}c=!0}c||(E5("Updated online screens: "+g.Sj(a.u)),a.u=b,a.V("screenChange"));HIa(a)},I5=function(a){isNaN(a.C)||g.Ko(a.C);
a.C=g.Io((0,g.A)(a.aA,a),0<a.D&&a.D<g.B()?2E4:1E4)},E5=function(a){v5("OnlineScreenService",a)},IIa=function(a){var b={};
g.Ab(a.I(),function(c){c.token?b[c.token]=c.id:this.Gd("Requesting availability of screen w/o lounge token.")});
return b},HIa=function(a){a=g.Kb(g.Db(a.u,function(b){return b}));
g.xb(a);a.length?g.Du("yt-remote-online-screen-ids",a.join(","),60):g.Fu("yt-remote-online-screen-ids")},J5=function(a){z5.call(this,"ScreenService");
this.D=a;this.u=this.B=null;this.C=[];this.F={};JIa(this)},LIa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.F[b]);var h=a.Rg();if(h=(c?x4(h,c):null)||x4(h,b)){h.uuid=b;var l=K5(a,h);G5(a.u,l,function(m){e(m?l:null)})}else c?KIa(a,c,(0,g.A)(function(m){var n=K5(this,new r4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));G5(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},MIa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},NIa=function(a,b,c){G5(a.u,b,c)},KIa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.xq(s5(a.D,"/pairing/get_lounge_token_batch"),e)},OIa=function(a){a.screens=a.B.Rg();
var b=a.F,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+u4(a.screens))},JIa=function(a){L5(a);
a.B=new C5(a.D);a.B.subscribe("screenChange",(0,g.A)(a.kM,a));OIa(a);a.C=oHa(g.Eu("yt-remote-automatic-screen-cache")||[]);L5(a);a.info("Initializing automatic screens: "+u4(a.C));a.u=new F5(a.D,(0,g.A)(a.Rg,a,!0));a.u.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},K5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=x4(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),PIa(a));L5(a);a.F[b.uuid]=b.id;g.Du("yt-remote-device-id-map",a.F,31536E3);return b},PIa=function(a){a=g.Me(a.C,function(b){return"shortLived"!=b.idType});
g.Du("yt-remote-automatic-screen-cache",g.Lc(a,mHa))},L5=function(a){a.F=g.Eu("yt-remote-device-id-map")||{}},M5=function(a,b,c){g.O.call(this);
this.ga=c;this.D=a;this.u=b;this.C=null},N5=function(a,b){a.C=b;
a.V("sessionScreen",a.C)},O5=function(a,b){v5(a.ga,b)},P5=function(a,b,c){M5.call(this,a,b,"CastSession");
var d=this;this.ea=c;this.B=null;this.X=(0,g.A)(this.mK,this);this.Z=(0,g.A)(this.vQ,this);this.W=g.Io(function(){QIa(d,null)},12E4);
this.K=this.F=this.I=this.N=0;this.da=!1;this.U="unknown"},Q5=function(a,b){g.Ko(a.K);
a.K=0;0==b?RIa(a):a.K=g.Io(function(){RIa(a)},b)},RIa=function(a){SIa(a,"getLoungeToken");
g.Ko(a.F);a.F=g.Io(function(){TIa(a,null)},3E4)},SIa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Sj(void 0));
var c={};c.type=b;a.B?a.B.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.A)(function(){O5(this,"Failed to send message: "+b+".")},a)):O5(a,"Sending yt message without session: "+g.Sj(c))},R5=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.eE(b,function(c){N5(a,c)},function(){return a.gg()},5)):a.gg(Error("Waiting for session status timed out."))},VIa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new r4(b);UIa(a,d,function(e){e?(a.da=!0,K5(a.D,d),N5(a,d),a.U="unknown",Q5(a,c)):(g.Fo(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.gg())},5)},QIa=function(a,b){g.Ko(a.W);
a.W=0;b?a.ea.l4&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?VIa(a,{name:a.u.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Fo(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),R5(a,b.screenId))):(g.Fo(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),R5(a,b.screenId)):
R5(a,b.screenId):a.gg(Error("Waiting for session status timed out."))},TIa=function(a,b){g.Ko(a.F);
a.F=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.U=c,Q5(a,3E4)):(a.C&&(a.C.token=b.loungeToken,K5(a.D,a.C)),a.V("sessionScreen",a.C),a.da=!1,a.U="unknown",Q5(a,b.loungeTokenRefreshIntervalMs))},UIa=function(a,b,c,d){g.Ko(a.I);
a.I=0;NIa(a.D,b,function(e){e||0>d?c(e):a.I=g.Io(function(){UIa(a,b,c,d-1)},300)})},WIa=function(a){g.Ko(a.N);
a.N=0;g.Ko(a.I);a.I=0;g.Ko(a.W);a.W=0;g.Ko(a.F);a.F=0;g.Ko(a.K);a.K=0},S5=function(a,b,c){M5.call(this,a,b,"DialSession");
this.F=this.N=null;this.U="";this.Z=c;this.X=null;this.K=g.Ia;this.I=NaN;this.W=(0,g.A)(this.nK,this);this.B=g.Ia},XIa=function(a){a.B=a.D.dC(a.U,a.u.label,a.u.friendlyName,(0,g.A)(function(b){this.B=g.Ia;
N5(this,b)},a),(0,g.A)(function(b){this.B=g.Ia;
this.gg(b)},a))},YIa=function(a){var b={};
b.pairingCode=a.U;b.theme=a.Z;zHa()&&(b.env_useStageMdx=1);return g.Id(b)},T5=function(a,b){M5.call(this,a,b,"ManualSession");
this.B=g.Io((0,g.A)(this.qp,this,null),150)},U5=function(a,b){g.O.call(this);
this.D=b;this.B=a;this.N=b.appId||"233637DE";this.F=b.theme||"cl";this.U=b.disableCastApi||!1;this.u=null;this.K=!1;this.C=[];this.I=(0,g.A)(this.oP,this)},ZIa=function(a,b){return b?g.bb(a.C,function(c){return s4(b,c.label)},a):null},V5=function(a){v5("Controller",a)},wIa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},W5=function(a){return a.K||!!a.C.length||!!a.u},X5=function(a,b,c){b!=a.u&&(g.ag(a.u),(a.u=b)?(c?a.V("yt-remote-cast2-receiver-resumed",
b.u):a.V("yt-remote-cast2-receiver-selected",b.u),b.subscribe("sessionScreen",(0,g.A)(a.oG,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.u.qp(null)):a.V("yt-remote-cast2-session-change",null))},$Ia=function(a){var b=a.B.cC(),c=a.u&&a.u.u;
a=g.Lc(b,function(d){c&&s4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=ZIa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},fJa=function(a,b,c,d){d.disableCastApi?Y5("Cannot initialize because disabled by Mdx config."):aJa()?bJa(b,d)&&(Z5(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?cJa(a,c):(window.__onGCastApiAvailable=function(e,f){e?cJa(a,c):($5("Failed to load cast API: "+f),a6(!1),Z5(!1),g.Fu("yt-remote-cast-available"),g.Fu("yt-remote-cast-receiver"),
dJa(),c(!1))},d.loadCastApiSetupScript?g.Uo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?GHa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?F4():(FHa(),E4(eJa.map(DHa))))):Y5("Cannot initialize because not running Chrome")},dJa=function(){Y5("dispose");
var a=b6();a&&a.dispose();g.Da("yt.mdx.remote.cloudview.instance_",null,void 0);gJa(!1);g.Qo(c6);c6.length=0},d6=function(){return!!g.Eu("yt-remote-cast-installed")},hJa=function(){var a=g.Eu("yt-remote-cast-receiver");
return a?a.friendlyName:null},iJa=function(){Y5("clearCurrentReceiver");
g.Fu("yt-remote-cast-receiver")},jJa=function(){return d6()?b6()?b6().getCastSession():($5("getCastSelector: Cast is not initialized."),null):($5("getCastSelector: Cast API is not installed!"),null)},f6=function(){d6()?b6()?e6()?(Y5("Requesting cast selector."),b6().requestSession()):(Y5("Wait for cast API to be ready to request the session."),c6.push(g.Po("yt-remote-cast2-api-ready",f6))):$5("requestCastSelector: Cast is not initialized."):$5("requestCastSelector: Cast API is not installed!")},g6=
function(a,b){e6()?b6().setConnectedScreenStatus(a,b):$5("setConnectedScreenStatus called before ready.")},aJa=function(){var a=0<=g.Tc.search(/ (CrMo|Chrome|CriOS)\//);
return g.wB||a},kJa=function(a,b){b6().init(a,b)},bJa=function(a,b){var c=!1;
b6()||(c=new U5(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.Du("yt-remote-cast-available",d);p4("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){Y5("onReceiverSelected: "+d.friendlyName);
g.Du("yt-remote-cast-receiver",d);p4("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){Y5("onReceiverResumed: "+d.friendlyName);
g.Du("yt-remote-cast-receiver",d);p4("yt-remote-cast2-receiver-resumed",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){Y5("onSessionChange: "+t4(d));
d||g.Fu("yt-remote-cast-receiver");p4("yt-remote-cast2-session-change",d)}),g.Da("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
Y5("cloudview.createSingleton_: "+c);return c},b6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},cJa=function(a,b){a6(!0);
Z5(!1);kJa(a,function(c){c?(gJa(!0),g.Ro("yt-remote-cast2-api-ready")):($5("Failed to initialize cast API."),a6(!1),g.Fu("yt-remote-cast-available"),g.Fu("yt-remote-cast-receiver"),dJa());b(c)})},Y5=function(a){v5("cloudview",a)},$5=function(a){v5("cloudview",a)},a6=function(a){Y5("setCastInstalled_ "+a);
g.Du("yt-remote-cast-installed",a)},e6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},gJa=function(a){Y5("setApiReady_ "+a);
g.Da("yt.mdx.remote.cloudview.apiReady_",a,void 0)},Z5=function(a){g.Da("yt.mdx.remote.cloudview.initializing_",a,void 0)},h6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.K=this.N=0;this.u=null;this.hasNext=this.rj=!1;this.U=this.I=this.B=this.F=0;this.D=NaN;this.C=!1;this.reset(a)},i6=function(a){a.audioTrackId=null;
a.u=null;a.playerState=-1;a.rj=!1;a.hasNext=!1;a.N=0;a.K=g.B();a.F=0;a.B=0;a.I=0;a.U=0;a.D=NaN;a.C=!1},j6=function(a){return a.Gb()?(g.B()-a.K)/1E3:0},k6=function(a,b){a.N=b;
a.K=g.B()},l6=function(a){switch(a.playerState){case 1:case 1081:return(g.B()-a.K)/1E3+a.N;
case -1E3:return 0}return a.N},m6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&i6(a)},n6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Ub(a.u);b.hasPrevious=a.rj;b.hasNext=a.hasNext;b.playerTime=a.N;b.playerTimeAt=a.K;b.seekableStart=a.F;b.seekableEnd=a.B;b.duration=a.I;b.loadedTime=a.U;b.liveIngestionTime=a.D;return b},p6=function(a,b){g.O.call(this);
this.La=0;this.C=a;this.F=[];this.D=new sIa;this.B=this.u=null;this.N=(0,g.A)(this.QN,this);this.I=(0,g.A)(this.Wr,this);this.K=(0,g.A)(this.PN,this);this.U=(0,g.A)(this.XN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.oA,this),lJa(this))):c=3;0!=c&&(b?this.oA(c):g.Io((0,g.A)(function(){this.oA(c)},this),0));
var d=jJa();d&&o6(this,d);this.subscribe("yt-remote-cast2-session-change",this.U)},q6=function(a){return new h6(a.C.getPlayerContextData())},lJa=function(a){g.Ab("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Pa(this.lP,b),this))},a)},mJa=function(a){g.Ab(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},r6=function(a){return 1==a.getState()},s6=function(a,b){var c=a.D;
50>c.u.length+c.B.length&&a.D.B.push(b)},u6=function(a,b,c){var d=q6(a);
k6(d,c);-1E3!=d.playerState&&(d.playerState=b);t6(a,d)},v6=function(a,b,c){a.C.sendMessage(b,c)},t6=function(a,b){mJa(a);
a.C.setPlayerContextData(n6(b));lJa(a)},o6=function(a,b){a.B&&(a.B.removeUpdateListener(a.N),a.B.removeMediaListener(a.I),a.Wr(null));
a.B=b;a.B&&(v5("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.N),a.B.addMediaListener(a.I),a.B.media.length&&a.Wr(a.B.media[0]))},nJa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=q6(a);b.contentId!=d.videoId&&v5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;k6(d,a.u.getEstimatedTime());t6(a,d)}else v5("CP","No cast media video. Ignoring state update.")},w6=function(a,b,c){return(0,g.A)(function(d){this.Gd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gd("Retrying "+b+" using MDx browser channel."),v6(this,b,c))},a)},x6=function(a,b,c){g.O.call(this);
this.F=NaN;this.Z=!1;this.N=this.K=this.W=this.X=NaN;this.U=[];this.D=this.I=this.C=this.Ib=this.u=null;this.ga=a;this.U.push(g.jp(window,"beforeunload",(0,g.A)(this.YL,this)));this.B=[];this.Ib=new h6;this.ea=b.id;this.da=b.idType;this.u=oJa(this,c);this.u.subscribe("handlerOpened",this.UN,this);this.u.subscribe("handlerClosed",this.RN,this);this.u.subscribe("handlerError",this.SN,this);this.u.subscribe("handlerMessage",this.TN,this);this.u.Fv(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Ib.videoId;g.Gu()&&g.Du("yt-remote-session-video-id",d)},this)},y6=function(a){v5("conn",a)},oJa=function(a,b){return new o5(s5(a.ga,"/bc"),b,!1,function(){return a.hC()},"shortLived"==a.da)},z6=function(a,b){a.V("proxyStateChange",b)},pJa=function(a){a.F=g.Io((0,g.A)(function(){y6("Connecting timeout");
this.Oo(1)},a),2E4)},A6=function(a){g.Ko(a.F);
a.F=NaN},B6=function(a){g.Ko(a.X);
a.X=NaN},qJa=function(a){C6(a);
a.W=g.Io((0,g.A)(function(){D6(this,"getNowPlaying")},a),2E4)},C6=function(a){g.Ko(a.W);
a.W=NaN},sJa=function(a,b){b&&(A6(a),B6(a));
var c=q5(a.u)&&isNaN(a.F);b==c?b&&(z6(a,1),D6(a,"getSubtitlesTrack")):b?(a.dE()&&a.Ib.reset(),z6(a,1),D6(a,"getNowPlaying"),rJa(a)):a.Oo(1)},tJa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ib.videoId&&(g.Pb(b.params)?a.Ib.u=null:a.Ib.u=b.params,a.V("remotePlayerChange"))},uJa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ib.listId=b.params.listId||a.Ib.listId;m6(a.Ib,c,d);a.V("remoteQueueChange")},wJa=function(a,b){b.params=b.params||{};
uJa(a,b);vJa(a,b);a.V("autoplayDismissed")},vJa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
k6(a.Ib,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ib.playerState&&(c=-1E3);a.Ib.playerState=c;c=Number(b.params.loadedTime);a.Ib.U=isNaN(c)?0:c;c=Number(b.params.duration);a.Ib.I=isNaN(c)?0:c;c=a.Ib;var d=Number(b.params.liveIngestionTime);c.D=d;c.C=isNaN(d)?!1:!0;c=a.Ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.F=isNaN(d)?0:d;c.B=isNaN(e)?0:e;1==a.Ib.playerState?qJa(a):C6(a);a.V("remotePlayerChange")},xJa=function(a,b){if(-1E3!=
a.Ib.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ib.playerState=c;c=parseInt(b.params.currentTime,10);k6(a.Ib,isNaN(c)?0:c);a.V("remotePlayerChange")}},yJa=function(a,b){var c="true"==b.params.muted;
a.Ib.volume=parseInt(b.params.volume,10);a.Ib.muted=c;a.V("remotePlayerChange")},zJa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},AJa=function(a,b){var c="true"==b.params.hasNext;
a.Ib.rj="true"==b.params.hasPrevious;a.Ib.hasNext=c;a.V("previousNextChange")},rJa=function(a){g.Ko(a.N);
a.N=g.Io((0,g.A)(a.Oo,a,1),864E5)},D6=function(a,b,c){c?y6("Sending: action="+b+", params="+g.Sj(c)):y6("Sending: action="+b);
a.u.sendMessage(b,c)},E6=function(a){z5.call(this,"ScreenServiceProxy");
this.Kf=a;this.u=[];this.u.push(this.Kf.$_s("screenChange",(0,g.A)(this.rK,this)));this.u.push(this.Kf.$_s("onlineScreenChange",(0,g.A)(this.SO,this)))},EJa=function(a,b){yHa();
if(!D4||!D4.get("yt-remote-disable-remote-module-for-dev")){b=g.M("MDX_CONFIG")||b;qHa();B4();F6||(F6=new r5(b?b.loungeApiHost:void 0),zHa()&&(F6.u="/api/loungedev"));G6||(G6=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Da("yt.mdx.remote.deferredProxies_",G6,void 0));BJa();var c=H6();if(!c){var d=new J5(F6);g.Da("yt.mdx.remote.screenService_",d,void 0);c=H6();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});fJa(a,d,function(h){h?I6()&&g6(I6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){p4("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ha("yt.mdx.remote.initialized_")){g.Da("yt.mdx.remote.initialized_",!0,void 0);
J6("Initializing: "+g.Sj(b));K6.push(g.Po("yt-remote-cast2-availability-change",function(){p4("yt-remote-receiver-availability-change")}));
K6.push(g.Po("yt-remote-cast2-receiver-selected",function(){L6(null);p4("yt-remote-auto-connect","cast-selector-receiver")}));
K6.push(g.Po("yt-remote-cast2-receiver-resumed",function(){p4("yt-remote-receiver-resumed","cast-selector-receiver")}));
K6.push(g.Po("yt-remote-cast2-session-change",CJa));K6.push(g.Po("yt-remote-connection-change",function(h){h?g6(I6(),"YouTube TV"):M6()||(g6(null,null),iJa())}));
e=N6();b.isAuto&&(e.id+="#dial");g.Yo("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);J6(" -- with channel params: "+g.Sj(e));e?(g.Du("yt-remote-session-app",e.app),g.Du("yt-remote-session-name",e.name)):(g.Fu("yt-remote-session-app"),g.Fu("yt-remote-session-name"));g.Da("yt.mdx.remote.channelParams_",e,void 0);c.start();I6()||DJa()}}},FJa=function(){var a=H6().Kf.$_gos();
var b=O6();b&&P6()&&(w4(a,b)||a.push(b));return pHa(a)},Q6=function(){var a=GJa();
!a&&d6()&&hJa()&&(a={key:"cast-selector-receiver",name:hJa()});return a},GJa=function(){var a=FJa(),b=O6();
b||(b=M6());return g.bb(a,function(c){return b&&s4(b,c.key)?!0:!1})},O6=function(){var a=I6();
if(!a)return null;var b=H6().Rg();return x4(b,a)},CJa=function(a){J6("remote.onCastSessionChange_: "+t4(a));
if(a){var b=O6();if(b&&b.id==a.id){if(g6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))R6&&(R6.token=a),(b=P6())&&b.Fv(a)}else b&&S6(),T6(a,1)}else P6()&&S6()},S6=function(){e6()?b6().stopSession():$5("stopSession called before API ready.");
var a=P6();a&&(a.disconnect(1),U6(null))},V6=function(){var a=P6();
return!!a&&3!=a.getProxyState()},J6=function(a){v5("remote",a)},H6=function(){if(!W6){var a=g.Ha("yt.mdx.remote.screenService_");
W6=a?new E6(a):null}return W6},I6=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},HJa=function(a){g.Da("yt.mdx.remote.currentScreenId_",a,void 0)},IJa=function(){return g.Ha("yt.mdx.remote.connectData_")},L6=function(a){g.Da("yt.mdx.remote.connectData_",a,void 0)},P6=function(){return g.Ha("yt.mdx.remote.connection_")},U6=function(a){var b=P6();
L6(null);a||HJa("");g.Da("yt.mdx.remote.connection_",a,void 0);G6&&(g.Ab(G6,function(c){c(a)}),G6.length=0);
b&&!a?p4("yt-remote-connection-change",!1):!b&&a&&p4("yt-remote-connection-change",!0)},M6=function(){var a=g.Gu();
if(!a)return null;var b=H6();if(!b)return null;b=b.Rg();return x4(b,a)},T6=function(a,b){I6();
O6()&&O6();if(X6)R6=a;else{HJa(a.id);var c=new x6(F6,a,N6());c.connect(b,IJa());c.subscribe("beforeDisconnect",function(d){p4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){P6()&&(P6(),U6(null))});
c.subscribe("browserChannelAuthError",function(){var d=O6();d&&"shortLived"==d.idType&&(e6()?b6().handleBrowserChannelAuthError():$5("refreshLoungeToken called before API ready."))});
U6(c)}},DJa=function(){var a=M6();
a?(J6("Resume connection to: "+t4(a)),T6(a,0)):(C4(),iJa(),J6("Skipping connecting because no session screen found."))},BJa=function(){var a=N6();
if(g.Pb(a)){a=A4();var b=g.Eu("yt-remote-session-name")||"",c=g.Eu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Da("yt.mdx.remote.channelParams_",a,void 0)}},N6=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},Y6=function(a,b,c){g.C.call(this);
var d=this;this.B=a;this.J=b;this.wb=c;this.events=new g.YN(this);this.W=this.events.P(this.J,"onVolumeChange",function(e){JJa(d,e)});
this.F=!1;this.suggestion=null;this.I=new g.VK(64);this.u=new g.J(this.uH,500,this);this.C=new g.J(this.vH,1E3,this);this.N=new G4(this.OR,0,this);this.D={};this.U=new g.J(this.WH,1E3,this);this.K=new H4(this.seekTo,1E3,this);this.X=g.Ia;g.E(this,this.events);this.events.P(b,"onCaptionsTrackListChanged",this.BO);this.events.P(b,"captionschanged",this.NN);this.events.P(b,"captionssettingschanged",this.zH);this.events.P(b,"videoplayerreset",this.hv);this.events.P(b,"mdxautoplaycancel",function(){d.wb.wD()});
a=this.wb;a.ma();a.subscribe("proxyStateChange",this.jG,this);a.subscribe("remotePlayerChange",this.hs,this);a.subscribe("remoteQueueChange",this.hv,this);a.subscribe("previousNextChange",this.gG,this);a.subscribe("nowAutoplaying",this.bG,this);a.subscribe("autoplayDismissed",this.BF,this);g.E(this,this.u);g.E(this,this.C);g.E(this,this.N);g.E(this,this.U);g.E(this,this.K);this.zH();this.hv();this.hs()},JJa=function(a,b){if(Z6(a)){a.wb.unsubscribe("remotePlayerChange",a.hs,a);
var c=Math.round(b.volume),d=!!b.muted,e=q6(a.wb);if(c!==e.volume||d!==e.muted)a.wb.setVolume(c,d),a.U.start();a.wb.subscribe("remotePlayerChange",a.hs,a)}},KJa=function(a){a.Bb(0);
a.u.stop();a.tb(new g.VK(64))},$6=function(a,b){if(Z6(a)&&!a.F){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Wb(c,b));a.wb.gC(a.J.getVideoData(1).videoId,c);a.D=q6(a.wb).u}},a7=function(a,b){var c=a.J.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.wb.playVideo(c.videoId,b,d,e,c.playerParams,c.ea,cHa(c));a.tb(new g.VK(1))},LJa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{zE:1});
c&&c.length?(a.J.setOption("captions","track",b),a.F=!1):(a.J.loadModule("captions"),a.F=!0)}else a.J.setOption("captions","track",{})},Z6=function(a){return q6(a.wb).videoId===a.J.getVideoData(1).videoId},b7=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",T:{role:"dialog"},R:[{G:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",R:[{G:"div",L:"ytp-mdx-manual-pairing-popup-title",ba:"Connecting to your TV on web using a code will be going away soon"},{G:"div",L:"ytp-mdx-manual-pairing-popup-buttons",R:[{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],ba:"Learn more"},{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],ba:"OK"}]}]}]});this.u=new g.DM(this,250);this.learnMoreButton=
this.ha("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ha("ytp-mdx-manual-pairing-popup-ok");g.E(this,this.u);this.P(this.learnMoreButton,"click",this.B);this.P(this.okButton,"click",this.C)},c7=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",T:{role:"dialog"},R:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",R:[{G:"div",L:"ytp-mdx-popup-title",ba:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",ba:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",R:[{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-cancel"],ba:"Cancel"},{G:"button",ia:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],ba:"Confirm"}]}]}]});this.u=new g.DM(this,250);this.cancelButton=this.ha("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ha("ytp-mdx-privacy-popup-confirm");g.E(this,this.u);this.P(this.cancelButton,"click",this.B);this.P(this.confirmButton,"click",this.C)},d7=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",R:[{G:"div",L:"ytp-remote-display-status",R:[{G:"div",L:"ytp-remote-display-status-icon",R:[g.ena()]},{G:"div",L:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.api=a;this.u=new g.DM(this,250);g.E(this,this.u);this.P(a,"presentingplayerstatechange",this.B);MJa(this,a.Va())},MJa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.vK("Error on $RECEIVER_NAME",c):b.Gb()||g.U(b,4)?g.vK("Playing on $RECEIVER_NAME",c):g.vK("Connected to $RECEIVER_NAME",c);a.za("statustext",c);a.u.show()}else a.u.hide()},e7=function(a,b){g.sR.call(this,"Play on",0,a,b);
this.J=a;this.gm={};this.P(a,"onMdxReceiversChange",this.F);this.P(a,"presentingplayerstatechange",this.F);this.F()},f7=function(a){g.hO.call(this,a);
this.ji={key:v4(),name:"This computer"};this.rh=null;this.subscriptions=[];this.Pz=this.wb=null;this.gm=[this.ji];this.vl=this.ji;this.Nc=new g.VK(64);this.UE=0;this.Qe=-1;this.wp=null;this.ls=this.Nu=!1;this.Mn=this.Lp=null;if(!g.HD(this.player.S())){a=this.player;var b=g.MN(a);b&&(b=b.Il())&&(b=new e7(a,b),g.E(this,b));b=new d7(a);g.E(this,b);g.WN(a,b.element,4);this.Lp=new c7;g.E(this,this.Lp);g.WN(a,this.Lp.element,4);g.Q(this.player.S().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.Q(this.player.S().experiments,"deprecate_pair_servlet_enabled")&&(this.wp=new b7,g.E(this,this.wp),g.WN(a,this.wp.element,4));this.ls=!!M6();this.Nu=!!g.Eu("yt-remote-manual-pairing-warning-shown")}},g7=function(a){a.Mn&&(a.player.removeEventListener("presentingplayerstatechange",a.Mn),a.Mn=null)},NJa=function(a,b,c){a.Nc=c;
a.player.V("presentingplayerstatechange",new g.bK(c,b))},OJa=function(a,b,c){var d=!1;
1===b?d=!a.ls:2===b&&(d=!a.Nu);d&&g.dK(c,8)&&(a.player.pauseVideo(),g7(a))},h7=function(a,b){if(b.key!==a.vl.key)if(b.key===a.ji.key)S6();
else{if(a.wp&&!a.Nu&&b!==a.ji&&"cast-selector-receiver"!==b.key&&g.SD(a.player.S()))PJa(a);else{var c;(c=!g.Q(a.player.S().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.ls||!a.Lp);(c?0:g.SD(a.player.S())||g.WD(a.player.S()))&&QJa(a)}a.vl=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.S().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.Ma(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ea,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=cHa(c))&&(d.locationInfo=c);c=d}J6("Connecting to: "+g.Sj(b));"cast-selector-receiver"==b.key?(L6(c||null),c=c||null,
e6()?b6().setLaunchParams(c):$5("setLaunchParams called before ready.")):!c&&V6()&&I6()==b.key?p4("yt-remote-connection-change",!0):(S6(),L6(c||null),c=H6().Rg(),(c=x4(c,b.key))&&T6(c,1))}},QJa=function(a){a.player.Va().Gb()?a.player.pauseVideo():(a.Mn=function(b){OJa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Mn));
a.Lp&&a.Lp.Ec();P6()||(X6=!0)},PJa=function(a){a.player.Va().Gb()?a.player.pauseVideo():(a.Mn=function(b){OJa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Mn));
a.wp&&a.wp.Ec();P6()||(X6=!0)},QHa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},W4={"'":"\\'"},RJa={},lHa={NS:"atp",d2:"ska",Z0:"que",h_:"mus",b2:"sus",BW:"dsp",v1:"seq",MZ:"mic",AV:"dpa"},D4,z4="",EHa=AHa("loadCastFramework")||AHa("loadCastApplicationFramework"),eJa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(G4,g.C);g.k=G4.prototype;g.k.gK=function(a){this.D=arguments;this.u=!1;this.gb?this.C=g.B()+this.Lf:this.gb=g.Rm(this.F,this.Lf)};
g.k.stop=function(){this.gb&&(g.z.clearTimeout(this.gb),this.gb=null);this.C=null;this.u=!1;this.D=[]};
g.k.pause=function(){++this.B};
g.k.resume=function(){this.B&&(--this.B,!this.B&&this.u&&(this.u=!1,this.I.apply(null,this.D)))};
g.k.ca=function(){this.stop();G4.Ed.ca.call(this)};
g.k.hK=function(){this.C?(this.gb=g.Rm(this.F,this.C-g.B()),this.C=null):(this.gb=null,this.B?this.u=!0:(this.u=!1,this.I.apply(null,this.D)))};g.u(H4,g.C);g.k=H4.prototype;g.k.YB=function(a){this.C=arguments;this.gb||this.B?this.u=!0:I4(this)};
g.k.stop=function(){this.gb&&(g.z.clearTimeout(this.gb),this.gb=null,this.u=!1,this.C=null)};
g.k.pause=function(){this.B++};
g.k.resume=function(){this.B--;this.B||!this.u||this.gb||(this.u=!1,I4(this))};
g.k.ca=function(){g.C.prototype.ca.call(this);this.stop()};K4.prototype.stringify=function(a){return g.z.JSON.stringify(a,void 0)};
K4.prototype.parse=function(a){return g.z.JSON.parse(a,void 0)};var M4=new g.gm;g.u(HHa,g.Kl);O4.prototype.u=null;O4.prototype.getOptions=function(){var a;(a=this.u)||(a={},JHa(this)&&(a[0]=!0,a[1]=!0),a=this.u=a);return a};var i7;g.Sa(IHa,O4);i7=new IHa;g.k=P4.prototype;g.k.Em=null;g.k.Di=!1;g.k.gq=null;g.k.YA=null;g.k.Pp=null;g.k.Zp=null;g.k.ol=null;g.k.im=null;g.k.Nn=null;g.k.De=null;g.k.Ys=0;g.k.Hi=null;g.k.ew=null;g.k.fl=null;g.k.yq=-1;g.k.jH=!0;g.k.Ym=!1;g.k.Uw=0;g.k.vv=null;var OHa={},S4={};g.k=P4.prototype;g.k.setTimeout=function(a){this.F=a};
g.k.OQ=function(a){a=a.target;var b=this.vv;b&&3==a5(a)?b.YB():this.eI(a)};
g.k.eI=function(a){try{if(a==this.De)a:{var b=a5(this.De),c=this.De.I,d=this.De.getStatus();if(g.ye&&!g.ce(10)||g.Ae&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.zg&&!c5(this.De))break a;this.Ym||4!=b||7==c||(8==c||0>=d?this.u.mi(3):this.u.mi(2));X4(this);var e=this.De.getStatus();this.yq=e;var f=c5(this.De);(this.Di=200==e)?(4==b&&U4(this),this.I?(PHa(this,b,f),g.zg&&this.Di&&3==b&&(this.D.ya(this.C,"tick",this.HQ),this.C.start())):T4(this,f),this.Di&&!this.Ym&&(4==b?this.u.wt(this):(this.Di=
!1,R4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.fl=3,N4(13)):(this.fl=0,N4(14)),U4(this),V4(this))}}catch(h){this.De&&c5(this.De)}finally{}};
g.k.HQ=function(){var a=a5(this.De),b=c5(this.De);this.Ys<b.length&&(X4(this),PHa(this,a,b),this.Di&&4!=a&&R4(this))};
g.k.gQ=function(a){L4((0,g.A)(this.fQ,this,a),0)};
g.k.fQ=function(a){this.Ym||(X4(this),T4(this,a),R4(this))};
g.k.tG=function(a){L4((0,g.A)(this.eQ,this,a),0)};
g.k.eQ=function(a){this.Ym||(U4(this),this.Di=a,this.u.wt(this),this.u.mi(4))};
g.k.cancel=function(){this.Ym=!0;U4(this)};
g.k.oQ=function(){this.gq=null;var a=g.B();0<=a-this.YA?(2!=this.Zp&&this.u.mi(3),U4(this),this.fl=2,N4(18),V4(this)):SHa(this,this.YA-a)};
g.k.getLastError=function(){return this.fl};g.Sa(Z4,g.gm);var ZHa=/^https?$/i,SJa=["POST","PUT"];g.k=Z4.prototype;
g.k.send=function(a,b,c,d){if(this.u)throw Error("[goog.net.XhrIo] Object is active with another request="+this.U+"; newUri="+a);b=b?b.toUpperCase():"GET";this.U=a;this.C="";this.I=0;this.xa=b;this.ea=!1;this.D=!0;this.u=this.da?KHa(this.da):KHa(i7);this.Z=this.da?this.da.getOptions():i7.getOptions();this.u.onreadystatechange=(0,g.A)(this.hG,this);try{o4(b5(this,"Opening Xhr")),this.ka=!0,this.u.open(b,String(a),!0),this.ka=!1}catch(f){o4(b5(this,"Error opening Xhr: "+f.message));YHa(this,f);return}a=
c||"";var e=this.headers.clone();d&&hHa(d,function(f,h){e.set(h,f)});
d=g.bb(e.yh(),WHa);c=g.z.FormData&&a instanceof g.z.FormData;!g.fb(SJa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.u.setRequestHeader(h,f)},this);
this.Aa&&(this.u.responseType=this.Aa);"withCredentials"in this.u&&this.u.withCredentials!==this.ga&&(this.u.withCredentials=this.ga);try{aIa(this),0<this.K&&(this.X=VHa(this.u),o4(b5(this,"Will abort after "+this.K+"ms if incomplete, xhr2 "+this.X)),this.X?(this.u.timeout=this.K,this.u.ontimeout=(0,g.A)(this.aC,this)):this.W=g.Rm(this.aC,this.K,this)),o4(b5(this,"Sending request")),this.N=!0,this.u.send(a),this.N=!1}catch(f){o4(b5(this,"Send error: "+f.message)),YHa(this,f)}};
g.k.aC=function(){"undefined"!=typeof g.u_&&this.u&&(this.C="Timed out after "+this.K+"ms, aborting",this.I=8,b5(this,this.C),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.u&&this.D&&(b5(this,"Aborting"),this.D=!1,this.F=!0,this.u.abort(),this.F=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),$4(this))};
g.k.ca=function(){this.u&&(this.D&&(this.D=!1,this.F=!0,this.u.abort(),this.F=!1),$4(this,!0));Z4.Ed.ca.call(this)};
g.k.hG=function(){this.ma()||(this.ka||this.N||this.F?$Ha(this):this.nP())};
g.k.nP=function(){$Ha(this)};
g.k.isActive=function(){return!!this.u};
g.k.isComplete=function(){return 4==a5(this)};
g.k.getStatus=function(){try{return 2<a5(this)?this.u.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.u&&this.isComplete())return a=this.u.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.C?this.C:String(this.C)};g.k=bIa.prototype;g.k.Vw=null;g.k.Fg=null;g.k.wv=!1;g.k.bC=null;g.k.Tt=null;g.k.kz=null;g.k.Ww=null;g.k.La=null;g.k.Zj=-1;g.k.zq=null;g.k.Iq=null;g.k.connect=function(a){this.Ww=a;a=d5(this.u,null,this.Ww);N4(3);this.bC=g.B();var b=this.u.K;null!=b?(this.zq=b[0],(this.Iq=b[1])?(this.La=1,cIa(this)):(this.La=2,f5(this))):(m4(a,"MODE","init"),this.Fg=new P4(this,void 0,void 0,void 0),this.Fg.Em=this.Vw,Q4(this.Fg,a,!1,null,!0),this.La=0)};
g.k.cL=function(a){if(a)this.La=2,f5(this);else{N4(4);var b=this.u;b.Qi=b.sl.Zj;m5(b,9)}a&&this.mi(2)};
g.k.Wx=function(a){return this.u.Wx(a)};
g.k.abort=function(){this.Fg&&(this.Fg.cancel(),this.Fg=null);this.Zj=-1};
g.k.ZB=function(){return!1};
g.k.kG=function(a,b){this.Zj=a.yq;if(0==this.La)if(b){try{var c=this.B.parse(b)}catch(d){c=this.u;c.Qi=this.Zj;m5(c,2);return}this.zq=c[0];this.Iq=c[1]}else c=this.u,c.Qi=this.Zj,m5(c,2);else if(2==this.La)if(this.wv)N4(7),this.kz=g.B();else if("11111"==b){if(N4(6),this.wv=!0,this.Tt=g.B(),c=this.Tt-this.bC,!g.ye||g.ce(10)||500>c)this.Zj=200,this.Fg.cancel(),N4(12),e5(this.u,this,!0)}else N4(8),this.Tt=this.kz=g.B(),this.wv=!1};
g.k.wt=function(){this.Zj=this.Fg.yq;if(this.Fg.Di)0==this.La?this.Iq?(this.La=1,cIa(this)):(this.La=2,f5(this)):2==this.La&&((!g.ye||g.ce(10)?!this.wv:200>this.kz-this.Tt)?(N4(11),e5(this.u,this,!1)):(N4(12),e5(this.u,this,!0)));else{0==this.La?N4(9):2==this.La&&N4(10);var a=this.u;this.Fg.getLastError();a.Qi=this.Zj;m5(a,2)}};
g.k.Gs=function(){return this.u.Gs()};
g.k.isActive=function(){return this.u.isActive()};
g.k.mi=function(a){this.u.mi(a)};g.k=g5.prototype;g.k.Pi=null;g.k.er=null;g.k.sg=null;g.k.ae=null;g.k.Xw=null;g.k.Ut=null;g.k.QC=null;g.k.xt=null;g.k.Ur=0;g.k.eN=0;g.k.Cf=null;g.k.Al=null;g.k.ck=null;g.k.gn=null;g.k.sl=null;g.k.bw=null;g.k.pp=-1;g.k.TE=-1;g.k.Qi=-1;g.k.So=0;g.k.Do=0;g.k.Zm=8;g.Sa(eIa,g.Kl);g.Sa(fIa,g.Kl);g.k=g5.prototype;g.k.connect=function(a,b,c,d,e){N4(0);this.Xw=b;this.er=c||{};d&&void 0!==e&&(this.er.OSID=d,this.er.OAID=e);this.F?(L4((0,g.A)(this.iD,this,a),100),jIa(this)):this.iD(a)};
g.k.iD=function(a){this.sl=new bIa(this);this.sl.Vw=this.Pi;this.sl.B=this.D;this.sl.connect(a)};
g.k.ZB=function(){return 0==this.La};
g.k.getState=function(){return this.La};
g.k.rG=function(a){this.Al=null;nIa(this,a)};
g.k.qG=function(){this.ck=null;this.ae=new P4(this,this.B,"rpc",this.I);this.ae.Em=this.Pi;this.ae.Uw=0;var a=this.QC.clone();k4(a,"RID","rpc");k4(a,"SID",this.B);k4(a,"CI",this.bw?"0":"1");k4(a,"AID",this.pp);h5(this,a);if(!g.ye||g.ce(10))k4(a,"TYPE","xmlhttp"),Q4(this.ae,a,!0,this.xt,!1);else{k4(a,"TYPE","html");var b=this.ae,c=!!this.xt;b.Zp=3;b.ol=l4(a.clone());RHa(b,c)}};
g.k.kG=function(a,b){if(0!=this.La&&(this.ae==a||this.sg==a))if(this.Qi=a.yq,this.sg==a&&3==this.La)if(7<this.Zm){try{var c=this.D.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.ck){if(this.ae)if(this.ae.Pp+3E3<this.sg.Pp)j5(this),this.ae.cancel(),this.ae=null;else break a;l5(this);N4(19)}}else this.TE=c[1],0<this.TE-this.pp&&37500>c[2]&&this.bw&&0==this.Do&&!this.gn&&(this.gn=L4((0,g.A)(this.JN,this),6E3));else m5(this,11)}else b!=RJa.pV.u&&m5(this,11);else if(this.ae==
a&&j5(this),!g.nc(b)){c=this.D.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.pp=e[0];e=e[1];2==this.La?"c"==e[0]?(this.B=e[1],this.xt=e[2],e=e[3],null!=e?this.Zm=e:this.Zm=6,this.La=3,this.Cf&&this.Cf.eD(),this.QC=d5(this,this.Gs()?this.xt:null,this.Xw),oIa(this)):"stop"==e[0]&&m5(this,7):3==this.La&&("stop"==e[0]?m5(this,7):"noop"!=e[0]&&this.Cf&&this.Cf.dD(e),this.Do=0)}}};
g.k.JN=function(){null!=this.gn&&(this.gn=null,this.ae.cancel(),this.ae=null,l5(this),N4(20))};
g.k.wt=function(a){if(this.ae==a){j5(this);this.ae=null;var b=2}else if(this.sg==a)this.sg=null,b=1;else return;this.Qi=a.yq;if(0!=this.La)if(a.Di)1==b?(b=M4,b.dispatchEvent(new eIa(b,a.Nn?a.Nn.length:0,g.B()-a.Pp,this.So)),i5(this),this.C.length=0):oIa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Qi)){if(d=1==b)this.sg||this.Al||1==this.La||2<=this.So?d=!1:(this.Al=L4((0,g.A)(this.rG,this,a),pIa(this,this.So)),this.So++,d=!0);d=!(d||2==b&&l5(this))}if(d)switch(c){case 1:m5(this,
5);break;case 4:m5(this,10);break;case 3:m5(this,6);break;case 7:m5(this,12);break;default:m5(this,2)}}};
g.k.xL=function(a){if(!g.fb(arguments,this.La))throw Error("Unexpected channel state: "+this.La);};
g.k.xR=function(a){a?N4(2):(N4(1),qIa(this,8))};
g.k.Wx=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Z4;a.ga=!1;return a};
g.k.isActive=function(){return!!this.Cf&&this.Cf.isActive(this)};
g.k.mi=function(a){var b=M4;b.dispatchEvent(new fIa(b,a))};
g.k.Gs=function(){return!(!g.ye||g.ce(10))};
g.k=rIa.prototype;g.k.eD=function(){};
g.k.dD=function(){};
g.k.cD=function(){};
g.k.Jx=function(){};
g.k.ND=function(){return{}};
g.k.isActive=function(){return!0};g.k=sIa.prototype;g.k.isEmpty=function(){return g.gb(this.u)&&g.gb(this.B)};
g.k.clear=function(){this.u=[];this.B=[]};
g.k.contains=function(a){return g.fb(this.u,a)||g.fb(this.B,a)};
g.k.remove=function(a){var b=this.u;var c=(0,g.wBa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.B,a)};
g.k.Zf=function(){for(var a=[],b=this.u.length-1;0<=b;--b)a.push(this.u[b]);var c=this.B.length;for(b=0;b<c;++b)a.push(this.B[b]);return a};g.Sa(n5,g.C);g.k=n5.prototype;g.k.YP=function(){this.Lf=Math.min(3E5,2*this.Lf);this.C();this.B&&this.start()};
g.k.start=function(){var a=this.Lf+15E3*Math.random();g.rn(this.u,a);this.B=g.B()+a};
g.k.stop=function(){this.u.stop();this.B=0};
g.k.isActive=function(){return this.u.isActive()};
g.k.reset=function(){this.u.stop();this.Lf=5E3};g.Sa(o5,rIa);g.k=o5.prototype;g.k.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.k.Rf=function(a){return this.C.Rf(a)};
g.k.V=function(a,b){return this.C.V.apply(this.C,arguments)};
g.k.dispose=function(){this.W||(this.W=!0,g.ag(this.C),vIa(this),g.ag(this.B),this.B=null,this.X=function(){return""})};
g.k.ma=function(){return this.W};
g.k.connect=function(a,b,c){if(!this.u||2!=this.u.getState()){this.U="";this.B.stop();this.F=a||null;this.D=b||0;a=this.Z+"/test";b=this.Z+"/bind";var d=new g5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.da),e=this.u;e&&(e.Cf=null);d.Cf=this;this.u=d;p5(this);if(this.u){d=g.M("ID_TOKEN");var f=this.u.Pi||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.u.Pi=f}e?(3!=e.getState()&&0==lIa(e)||e.getState(),this.u.connect(a,b,this.I,e.B,e.pp)):c?this.u.connect(a,
b,this.I,c.sessionId,c.arrayId):this.u.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Wb(c,b);this.B.isActive()||2==(this.u?this.u.getState():0)?this.K.push(c):q5(this)&&(p5(this),kIa(this.u,c))};
g.k.eD=function(){this.B.reset();this.F=null;this.D=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)kIa(this.u,a[b])}this.V("handlerOpened")};
g.k.cD=function(a){var b=2==a&&401==this.u.Qi;4==a||b||this.B.start();this.V("handlerError",a,b)};
g.k.Jx=function(a){if(!this.B.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.ND=function(){var a={v:2};this.U&&(a.gsessionid=this.U);0!=this.D&&(a.ui=""+this.D);0!=this.N&&(a.ui=""+this.N);this.F&&g.Wb(a,this.F);return a};
g.k.dD=function(a){"S"==a[0]?this.U=a[1]:"gracefulReconnect"==a[0]?(this.B.start(),iIa(this.u)):this.V("handlerMessage",new tIa(a[0],a[1]))};
g.k.Fv=function(a){(this.I.loungeIdToken=a)||this.B.stop();if(this.ga&&this.u){var b=this.u.Pi||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.u.Pi=b}};
g.k.ZQ=function(){this.B.isActive();0==lIa(this.u)&&this.connect(this.F,this.D)};r5.prototype.D=function(a,b,c,d){b?a(d):a({text:c.responseText})};
r5.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
r5.prototype.F=function(a){a(Error("request timed out"))};var CIa=g.B(),u5=null,x5=Array(50),w5=-1,y5=!1;g.Sa(z5,g.O);z5.prototype.Rg=function(){return this.screens};
z5.prototype.contains=function(a){return!!w4(this.screens,a)};
z5.prototype.get=function(a){return a?x4(this.screens,a):null};
z5.prototype.info=function(a){v5(this.I,a)};g.u(A5,g.O);g.k=A5.prototype;g.k.start=function(){!this.u&&isNaN(this.gb)&&this.EG()};
g.k.stop=function(){this.u&&(this.u.abort(),this.u=null);isNaN(this.gb)||(g.Ko(this.gb),this.gb=NaN)};
g.k.ca=function(){this.stop();g.O.prototype.ca.call(this)};
g.k.EG=function(){this.gb=NaN;this.u=g.xq(s5(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.I},timeout:5E3,onSuccess:(0,g.A)(this.jK,this),onError:(0,g.A)(this.iK,this),onTimeout:(0,g.A)(this.kK,this)})};
g.k.jK=function(a,b){this.u=null;var c=b.screen||{};c.dialId=this.D;c.name=this.F;this.V("pairingComplete",new r4(c))};
g.k.iK=function(a){this.u=null;a.status&&404==a.status?this.B>=TJa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=TJa[this.B],this.gb=g.Io((0,g.A)(this.EG,this),a),this.B++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.kK=function(){this.u=null;this.V("pairingFailed",Error("Server not responding"))};
var TJa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(C5,z5);g.k=C5.prototype;g.k.start=function(){B5(this)&&this.V("screenChange");!g.Eu("yt-remote-lounge-token-expiration")&&GIa(this);g.Ko(this.u);this.u=g.Io((0,g.A)(this.start,this),1E4)};
g.k.add=function(a,b){B5(this);DIa(this,a);D5(this,!1);this.V("screenChange");b(a);a.token||GIa(this)};
g.k.remove=function(a,b){var c=B5(this);FIa(this,a)&&(D5(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.Yv=function(a,b,c,d){var e=B5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,D5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.ca=function(){g.Ko(this.u);C5.Ed.ca.call(this)};
g.k.eM=function(a){B5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}D5(this,!b);b&&v5(this.I,"Missed "+b+" lounge tokens.")};
g.k.dM=function(a){v5(this.I,"Requesting lounge tokens failed: "+a)};g.u(F5,g.O);g.k=F5.prototype;g.k.start=function(){var a=parseInt(g.Eu("yt-remote-fast-check-period")||"0",10);(this.D=g.B()-144E5<a?0:a)?I5(this):(this.D=g.B()+3E5,g.Du("yt-remote-fast-check-period",this.D),this.aA())};
g.k.isEmpty=function(){return g.Pb(this.u)};
g.k.update=function(){E5("Updating availability on schedule.");var a=this.I(),b=g.Db(this.u,function(c,d){return c&&!!x4(a,d)},this);
H5(this,b)};
g.k.ca=function(){g.Ko(this.C);this.C=NaN;this.B&&(this.B.abort(),this.B=null);g.O.prototype.ca.call(this)};
g.k.aA=function(){g.Ko(this.C);this.C=NaN;this.B&&this.B.abort();var a=IIa(this);if(n4(a)){var b=s5(this.F,"/pairing/get_screen_availability");this.B=t5(this.F,b,{lounge_token:g.Kb(a).join(",")},(0,g.A)(this.HP,this,a),(0,g.A)(this.GP,this))}else H5(this,{}),I5(this)};
g.k.HP=function(a,b){this.B=null;var c=g.Kb(IIa(this));if(g.yb(c,g.Kb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;H5(this,d);I5(this)}else this.Gd("Changing Screen set during request."),this.aA()};
g.k.GP=function(a){this.Gd("Screen availability failed: "+a);this.B=null;I5(this)};
g.k.Gd=function(a){v5("OnlineScreenService",a)};g.Sa(J5,z5);g.k=J5.prototype;g.k.start=function(){this.B.start();this.u.start();this.screens.length&&(this.V("screenChange"),this.u.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.B.add(a,b,c)};
g.k.remove=function(a,b,c){this.B.remove(a,b,c);this.u.update()};
g.k.Yv=function(a,b,c,d){this.B.contains(a)?this.B.Yv(a,b,c,d):(a="Updating name of unknown screen: "+a.name,v5(this.I,a),d(Error(a)))};
g.k.Rg=function(a){return a?this.screens:g.nb(this.screens,g.Me(this.C,function(b){return!this.contains(b)},this))};
g.k.cC=function(){return g.Me(this.Rg(!0),function(a){return!!this.u.u[a.id]},this)};
g.k.dC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new A5(this.D,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(h){g.ag(f);d(K5(this,h))},this));
f.subscribe("pairingFailed",function(h){g.ag(f);e(h)});
f.start();return(0,g.A)(f.stop,f)};
g.k.lK=function(a,b,c,d){g.xq(s5(this.D,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(e,f){var h=new r4(f.screen||{});if(!h.name||MIa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);MIa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(K5(this,h))},this),
onError:(0,g.A)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ca=function(){g.ag(this.B);g.ag(this.u);J5.Ed.ca.call(this)};
g.k.kM=function(){OIa(this);this.V("screenChange");this.u.update()};
J5.prototype.dispose=J5.prototype.dispose;g.Sa(M5,g.O);g.k=M5.prototype;g.k.getScreen=function(){return this.C};
g.k.gg=function(a){this.ma()||(a&&O5(this,""+a),this.C=null,this.V("sessionScreen",null))};
g.k.info=function(a){v5(this.ga,a)};
g.k.eC=function(){return null};
g.k.lA=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){O5(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ca=function(){this.lA("");M5.Ed.ca.call(this)};g.u(P5,M5);g.k=P5.prototype;g.k.kA=function(a){if(this.B){if(this.B==a)return;O5(this,"Overriding cast session with new session object");WIa(this);this.da=!1;this.U="unknown";this.B.removeUpdateListener(this.X);this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Z)}this.B=a;this.B.addUpdateListener(this.X);this.B.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Z);SIa(this,"getMdxSessionStatus")};
g.k.qp=function(a){this.info("launchWithParams no-op for Cast: "+g.Sj(a))};
g.k.stop=function(){this.B?this.B.stop((0,g.A)(function(){this.gg()},this),(0,g.A)(function(){this.gg(Error("Failed to stop receiver app."))},this)):this.gg(Error("Stopping cast device without session."))};
g.k.lA=function(){};
g.k.ca=function(){this.info("disposeInternal");WIa(this);this.B&&(this.B.removeUpdateListener(this.X),this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Z));this.B=null;M5.prototype.ca.call(this)};
g.k.vQ=function(a,b){if(!this.ma())if(b){var c=J4(b);if(g.Ma(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Sj(c));switch(d){case "mdxSessionStatus":QIa(this,c);break;case "loungeToken":TIa(this,c);break;default:O5(this,"Unknown youtube message: "+d)}}else O5(this,"Unable to parse message.")}else O5(this,"No data in message.")};
g.k.eE=function(a,b,c,d){g.Ko(this.N);this.N=0;LIa(this.D,this.u.label,a,this.u.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(O5(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.N=g.Io((0,g.A)(this.eE,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.eC=function(){return this.B};
g.k.mK=function(a){this.ma()||a||(O5(this,"Cast session died."),this.gg())};g.u(S5,M5);g.k=S5.prototype;g.k.kA=function(a){this.F=a;this.F.addUpdateListener(this.W)};
g.k.qp=function(a){this.X=a;this.K()};
g.k.stop=function(){this.B();this.B=g.Ia;g.Ko(this.I);this.F?this.F.stop((0,g.A)(this.gg,this,null),(0,g.A)(this.gg,this,"Failed to stop DIAL device.")):this.gg()};
g.k.ca=function(){this.B();this.B=g.Ia;g.Ko(this.I);this.F&&this.F.removeUpdateListener(this.W);this.F=null;M5.prototype.ca.call(this)};
g.k.nK=function(a){this.ma()||a||(O5(this,"DIAL session died."),this.B(),this.B=g.Ia,this.gg())};
g.k.Xy=function(a){this.U=v4();if(this.X){var b=new chrome.cast.DialLaunchResponse(!0,YIa(this));a(b);XIa(this)}else this.K=(0,g.A)(function(){g.Ko(this.I);this.K=g.Ia;this.I=NaN;var c=new chrome.cast.DialLaunchResponse(!0,YIa(this));a(c);XIa(this)},this),this.I=g.Io((0,g.A)(function(){this.K()},this),100)};
g.k.BM=function(a,b,c){LIa(this.D,this.N.receiver.label,a,this.u.friendlyName,(0,g.A)(function(d){d&&d.token?(N5(this,d),b(new chrome.cast.DialLaunchResponse(!1))):this.Xy(b,c)},this),(0,g.A)(function(d){O5(this,"Failed to get DIAL screen: "+d);
this.Xy(b,c)},this))};g.u(T5,M5);T5.prototype.stop=function(){this.gg()};
T5.prototype.kA=function(){};
T5.prototype.qp=function(){g.Ko(this.B);this.B=NaN;var a=x4(this.D.Rg(),this.u.label);a?N5(this,a):this.gg(Error("No such screen"))};
T5.prototype.ca=function(){g.Ko(this.B);this.B=NaN;M5.prototype.ca.call(this)};g.u(U5,g.O);g.k=U5.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.N);this.U||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.A)(this.rP,this);c=new chrome.cast.ApiConfig(c,(0,g.A)(this.mG,this),f,d,e);c.customDialLaunchCallback=(0,g.A)(this.eO,this);chrome.cast.initialize(c,(0,g.A)(function(){this.ma()||
(chrome.cast.addReceiverActionListener(this.I),zIa(),this.B.subscribe("onlineScreenChange",(0,g.A)(this.fC,this)),this.C=$Ia(this),chrome.cast.setCustomReceivers(this.C,g.Ia,(0,g.A)(function(h){this.Gd("Failed to set initial custom receivers: "+g.Sj(h))},this)),this.V("yt-remote-cast2-availability-change",W5(this)),b(!0))},this),(0,g.A)(function(h){this.Gd("Failed to initialize API: "+g.Sj(h));
b(!1)},this))};
g.k.gR=function(a,b){V5("Setting connected screen ID: "+a+" -> "+b);if(this.u){var c=this.u.getScreen();if(!a||c&&c.id!=a)V5("Unsetting old screen status: "+this.u.u.friendlyName),X5(this,null)}if(a&&b){if(!this.u){c=x4(this.B.Rg(),a);if(!c){V5("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){V5("setConnectedScreenStatus: Screen with id type to be short lived.");return}var d=ZIa(this,c);d||(V5("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,g.Ia,(0,g.A)(function(e){this.Gd("Failed to set initial custom receivers: "+g.Sj(e))},this)));
V5("setConnectedScreenStatus: new active receiver: "+d.friendlyName);X5(this,new T5(this.B,d),!0)}this.u.lA(b)}else V5("setConnectedScreenStatus: no screen.")};
g.k.hR=function(a){this.ma()?this.Gd("Setting connection data on disposed cast v2"):this.u?this.u.qp(a):this.Gd("Setting connection data without a session")};
g.k.pK=function(){this.ma()?this.Gd("Stopping session on disposed cast v2"):this.u?(this.u.stop(),X5(this,null)):V5("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.mG,this),(0,g.A)(this.KP,this))};
g.k.ca=function(){this.B.unsubscribe("onlineScreenChange",(0,g.A)(this.fC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.I);var a=wIa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.ag(this.u);g.O.prototype.ca.call(this)};
g.k.Gd=function(a){v5("Controller",a)};
g.k.oG=function(a,b){this.u==a&&(b||X5(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.oP=function(a,b){if(!this.ma())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),V5("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.u)if(this.u.u.label!=a.label)V5("onReceiverAction_: Stopping active receiver: "+this.u.u.friendlyName),this.u.stop();else{V5("onReceiverAction_: Casting to active receiver.");this.u.getScreen()&&this.V("yt-remote-cast2-session-change",this.u.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:X5(this,
new T5(this.B,a));break;case chrome.cast.ReceiverType.DIAL:X5(this,new S5(this.B,a,this.F));break;case chrome.cast.ReceiverType.CAST:X5(this,new P5(this.B,a,this.D));break;default:this.Gd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.u&&this.u.u.label==a.label?this.u.stop():this.Gd("Stopping receiver w/o session: "+a.friendlyName)}else this.Gd("onReceiverAction_ called without receiver.")};
g.k.eO=function(a){if(this.ma())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.u?this.u.u:null;if(!c||c.label!=b.label)return this.Gd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.u.getScreen())return V5("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.u.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);X5(this,new S5(this.B,b,this.F))}b=this.u;b.N=a;return b.N.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.BM,b,(b.N.extraData||{}).screenId||null)):new Promise((0,g.A)(b.Xy,b))};
g.k.mG=function(a){if(!this.ma()){V5("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.u)if(b.receiverType==chrome.cast.ReceiverType.CAST)V5("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),X5(this,new P5(this.B,b,this.D),!0);else{this.Gd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.u.u,d=x4(this.B.Rg(),c.label);d&&s4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(V5("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ag(this.u),this.u=new P5(this.B,b,this.D),this.u.subscribe("sessionScreen",(0,g.A)(this.oG,this,this.u)),this.u.qp(null));this.u.kA(a)}}};
g.k.oK=function(){return this.u?this.u.eC():null};
g.k.KP=function(a){this.ma()||(this.Gd("Failed to estabilish a session: "+g.Sj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&X5(this,null))};
g.k.rP=function(a){V5("Receiver availability updated: "+a);if(!this.ma()){var b=W5(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;W5(this)!=b&&this.V("yt-remote-cast2-availability-change",W5(this))}};
g.k.fC=function(){this.ma()||(this.C=$Ia(this),V5("Updating custom receivers: "+g.Sj(this.C)),chrome.cast.setCustomReceivers(this.C,g.Ia,(0,g.A)(function(){this.Gd("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",W5(this)))};
U5.prototype.setLaunchParams=U5.prototype.hR;U5.prototype.setConnectedScreenStatus=U5.prototype.gR;U5.prototype.stopSession=U5.prototype.pK;U5.prototype.getCastSession=U5.prototype.oK;U5.prototype.requestSession=U5.prototype.requestSession;U5.prototype.init=U5.prototype.init;U5.prototype.dispose=U5.prototype.dispose;var c6=[];g.k=h6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";i6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.u=a.trackData,this.rj=a.hasPrevious,this.hasNext=a.hasNext,this.N=a.playerTime,this.K=a.playerTimeAt,this.F=a.seekableStart,this.B=a.seekableEnd,this.I=a.duration,this.U=a.loadedTime,this.D=a.liveIngestionTime,this.C=!isNaN(this.D))};
g.k.Gb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.C?this.I+j6(this):this.I};
g.k.clone=function(){return new h6(n6(this))};g.u(p6,g.O);g.k=p6.prototype;g.k.getState=function(){return this.La};
g.k.play=function(){r6(this)?(this.u?this.u.play(null,g.Ia,w6(this,"play")):v6(this,"play"),u6(this,1,l6(q6(this))),this.V("remotePlayerChange")):s6(this,this.play)};
g.k.pause=function(){r6(this)?(this.u?this.u.pause(null,g.Ia,w6(this,"pause")):v6(this,"pause"),u6(this,2,l6(q6(this))),this.V("remotePlayerChange")):s6(this,this.pause)};
g.k.seekTo=function(a){if(r6(this)){if(this.u){var b=q6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Gb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ia,w6(this,"seekTo",{newTime:a}))}else v6(this,"seekTo",{newTime:a});u6(this,3,a);this.V("remotePlayerChange")}else s6(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(r6(this)){this.u?this.u.stop(null,g.Ia,w6(this,"stopVideo")):v6(this,"stopVideo");var a=q6(this);a.index=-1;a.videoId="";i6(a);t6(this,a);this.V("remotePlayerChange")}else s6(this,this.stop)};
g.k.setVolume=function(a,b){if(r6(this)){var c=q6(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){v5("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.Gd("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){v5("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.Gd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);v6(this,"setVolume",e)}c.muted=b;c.volume=a;t6(this,c)}else s6(this,g.Pa(this.setVolume,a,b))};
g.k.gC=function(a,b){if(r6(this)){var c=q6(this),d={videoId:a};b&&(c.u={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Sj(b.style),g.Wb(d,c.u));v6(this,"setSubtitlesTrack",d);t6(this,c)}else s6(this,g.Pa(this.gC,a,b))};
g.k.setAudioTrack=function(a,b){if(r6(this)){var c=b.getLanguageInfo().getId();v6(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=q6(this);d.audioTrackId=c;t6(this,d)}else s6(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=q6(this);c=c||0;var m={videoId:a,currentIndex:c};m6(l,a,c);void 0!==b&&(k6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Sj(h));v6(this,"setPlaylist",m);d||t6(this,l)};
g.k.lv=function(a,b){if(r6(this)){if(a&&b){var c=q6(this);m6(c,a,b);t6(this,c)}v6(this,"previous")}else s6(this,g.Pa(this.lv,a,b))};
g.k.nextVideo=function(a,b){if(r6(this)){if(a&&b){var c=q6(this);m6(c,a,b);t6(this,c)}v6(this,"next")}else s6(this,g.Pa(this.nextVideo,a,b))};
g.k.wD=function(){r6(this)?v6(this,"dismissAutoplay"):s6(this,this.wD)};
g.k.dispose=function(){if(3!=this.La){var a=this.La;this.La=3;this.V("proxyStateChange",a,this.La)}g.O.prototype.dispose.call(this)};
g.k.ca=function(){mJa(this);this.C=null;this.D.clear();o6(this,null);g.O.prototype.ca.call(this)};
g.k.oA=function(a){if((a!=this.La||2==a)&&3!=this.La&&0!=a){var b=this.La;this.La=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,g.gb(b.u)&&(b.u=b.B,b.u.reverse(),b.B=[]),a.u.pop().apply(this);else 3==a&&this.dispose()}};
g.k.lP=function(a,b){this.V(a,b)};
g.k.QN=function(a){if(!a)this.Wr(null),o6(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=q6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)v5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,t6(this,b)}};
g.k.Wr=function(a){v5("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.K);if(this.u=a)this.u.addUpdateListener(this.K),nJa(this),this.V("remotePlayerChange")};
g.k.PN=function(a){a?(nJa(this),this.V("remotePlayerChange")):this.Wr(null)};
g.k.DA=function(){v6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.XN=function(){var a=jJa();a&&o6(this,a)};
g.k.Gd=function(a){v5("CP",a)};g.u(x6,g.O);g.k=x6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Ib.listId=c);this.Ib.videoId=d;this.Ib.index=h||0;this.Ib.state=3;k6(this.Ib,m);this.D="UNSUPPORTED";y6("Connecting with setPlaylist and params: "+g.Sj(l));this.u.connect({method:"setPlaylist",
params:g.Sj(l)},a,tHa())}else y6("Connecting without params"),this.u.connect({},a,tHa());pJa(this)};
g.k.Fv=function(a){this.u.Fv(a)};
g.k.dispose=function(){this.ma()||(this.V("beforeDispose"),z6(this,3));g.O.prototype.dispose.call(this)};
g.k.ca=function(){A6(this);C6(this);B6(this);g.Ko(this.K);this.K=NaN;g.Ko(this.N);this.N=NaN;this.C=null;g.kp(this.U);this.U.length=0;this.u.dispose();g.O.prototype.ca.call(this);this.D=this.I=this.B=this.Ib=this.u=null};
g.k.YL=function(){this.Oo(2)};
g.k.UN=function(){y6("Channel opened");this.Z&&(this.Z=!1,B6(this),this.X=g.Io((0,g.A)(function(){y6("Timing out waiting for a screen.");this.Oo(1)},this),15E3));
xHa(uIa(this.u),this.ea)};
g.k.RN=function(){y6("Channel closed");isNaN(this.F)?C4(!0):C4();this.dispose()};
g.k.SN=function(a,b){C4();isNaN(this.yr())?(b&&"shortLived"==this.da&&this.V("browserChannelAuthError",a),y6("Channel error: "+a+" without reconnection"),this.dispose()):(this.Z=!0,y6("Channel error: "+a+" with reconnection in "+this.yr()+" ms"),z6(this,2))};
g.k.TN=function(a){a.params?y6("Received: action="+a.action+", params="+g.Sj(a.params)):y6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=J4(a.params.devices);this.B=g.Lc(a,function(c){return new q4(c)});
a=!!g.bb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
sJa(this,a);break;case "loungeScreenDisconnected":g.lb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
sJa(this,!1);break;case "remoteConnected":var b=new q4(J4(a.params.device));g.bb(this.B,function(c){return b?c.id==b.id:!1})||dHa(this.B,b);
break;case "remoteDisconnected":b=new q4(J4(a.params.device));g.lb(this.B,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":uJa(this,a);break;case "nowPlaying":wJa(this,a);break;case "onStateChange":vJa(this,a);break;case "onAdStateChange":xJa(this,a);break;case "onVolumeChanged":yJa(this,a);break;case "onSubtitlesTrackChanged":tJa(this,a);break;case "nowAutoplaying":zJa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.D=
a.params.autoplayMode;this.V("autoplayModeChange",this.D);"DISABLED"==this.D&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":AJa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:y6("Unrecognized action: "+a.action)}};
g.k.VQ=function(){if(this.C){var a=this.C;this.C=null;this.Ib.videoId!=a&&D6(this,"getNowPlaying")}};
g.k.SL=function(){var a=3;this.ma()||(a=0,isNaN(this.yr())?q5(this.u)&&isNaN(this.F)&&(a=1):a=2);return a};
g.k.Oo=function(a){y6("Disconnecting with "+a);A6(this);this.V("beforeDisconnect",a);1==a&&C4();vIa(this.u,a);this.dispose()};
g.k.QL=function(){var a=this.Ib;this.C&&(a=this.Ib.clone(),m6(a,this.C,a.index));return n6(a)};
g.k.iR=function(a){var b=new h6(a);b.videoId&&b.videoId!=this.Ib.videoId&&(this.C=b.videoId,g.Ko(this.K),this.K=g.Io((0,g.A)(this.VQ,this),5E3));var c=[];this.Ib.listId==b.listId&&this.Ib.videoId==b.videoId&&this.Ib.index==b.index||c.push("remoteQueueChange");this.Ib.playerState==b.playerState&&this.Ib.volume==b.volume&&this.Ib.muted==b.muted&&l6(this.Ib)==l6(b)&&g.Sj(this.Ib.u)==g.Sj(b.u)||c.push("remotePlayerChange");this.Ib.reset(a);g.Ab(c,function(d){this.V(d)},this)};
g.k.dE=function(){var a=this.u.I.id,b=g.bb(this.B,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.yr=function(){var a=this.u;return a.B.isActive()?a.B.B-g.B():NaN};
g.k.HL=function(){return this.D||"UNSUPPORTED"};
g.k.IL=function(){return this.I||""};
g.k.qK=function(){if(!isNaN(this.yr())){var a=this.u.B;g.sn(a.u);a.start()}};
g.k.eR=function(a,b){D6(this,a,b);rJa(this)};
g.k.hC=function(){var a=g.Eq("SID","")||"",b=g.Eq("SAPISID","")||"",c=g.Eq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.sf(g.Xe(a),2);b=g.sf(g.Xe(b),2);c=g.sf(g.Xe(c),2);return g.sf(g.Xe(a+","+b+","+c),2)};
x6.prototype.subscribe=x6.prototype.subscribe;x6.prototype.unsubscribeByKey=x6.prototype.Rf;x6.prototype.getProxyState=x6.prototype.SL;x6.prototype.disconnect=x6.prototype.Oo;x6.prototype.getPlayerContextData=x6.prototype.QL;x6.prototype.setPlayerContextData=x6.prototype.iR;x6.prototype.getOtherConnectedRemoteId=x6.prototype.dE;x6.prototype.getReconnectTimeout=x6.prototype.yr;x6.prototype.getAutoplayMode=x6.prototype.HL;x6.prototype.getAutoplayVideoId=x6.prototype.IL;x6.prototype.reconnect=x6.prototype.qK;
x6.prototype.sendMessage=x6.prototype.eR;x6.prototype.getXsrfToken=x6.prototype.hC;g.u(E6,z5);g.k=E6.prototype;g.k.Rg=function(a){return this.Kf.$_gs(a)};
g.k.contains=function(a){return!!this.Kf.$_c(a)};
g.k.get=function(a){return this.Kf.$_g(a)};
g.k.start=function(){this.Kf.$_st()};
g.k.add=function(a,b,c){this.Kf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Kf.$_r(a,b,c)};
g.k.Yv=function(a,b,c,d){this.Kf.$_un(a,b,c,d)};
g.k.ca=function(){for(var a=0,b=this.u.length;a<b;++a)this.Kf.$_ubk(this.u[a]);this.u.length=0;this.Kf=null;z5.prototype.ca.call(this)};
g.k.rK=function(){this.V("screenChange")};
g.k.SO=function(){this.V("onlineScreenChange")};
J5.prototype.$_st=J5.prototype.start;J5.prototype.$_gspc=J5.prototype.lK;J5.prototype.$_gsppc=J5.prototype.dC;J5.prototype.$_c=J5.prototype.contains;J5.prototype.$_g=J5.prototype.get;J5.prototype.$_a=J5.prototype.add;J5.prototype.$_un=J5.prototype.Yv;J5.prototype.$_r=J5.prototype.remove;J5.prototype.$_gs=J5.prototype.Rg;J5.prototype.$_gos=J5.prototype.cC;J5.prototype.$_s=J5.prototype.subscribe;J5.prototype.$_ubk=J5.prototype.Rf;var R6=null,X6=!1,F6=null,G6=null,W6=null,K6=[];g.u(Y6,g.C);g.k=Y6.prototype;g.k.ca=function(){g.C.prototype.ca.call(this);this.u.stop();this.C.stop();this.N.stop();this.X();var a=this.wb;a.unsubscribe("proxyStateChange",this.jG,this);a.unsubscribe("remotePlayerChange",this.hs,this);a.unsubscribe("remoteQueueChange",this.hv,this);a.unsubscribe("previousNextChange",this.gG,this);a.unsubscribe("nowAutoplaying",this.bG,this);a.unsubscribe("autoplayDismissed",this.BF,this);this.wb=this.B=null};
g.k.iC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.wb.La)if(Z6(this)){if(!q6(this.wb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":q6(this.wb).Gb()?this.wb.pause():this.wb.play();break;case "control_play":this.wb.play();break;case "control_pause":this.wb.pause();break;case "control_seek":this.K.YB(c[0],c[1]);break;case "control_subtitles_set_track":$6(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();a7(this,0===c?void 0:c);break;case "control_seek":a7(this,c[0]);break;case "control_subtitles_set_track":$6(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.NN=function(a){this.N.gK(a)};
g.k.OR=function(a){this.iC("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.zH=function(){var a=this.J.getOption("captions","track");g.Pb(a)||$6(this,a)};
g.k.Bb=function(a){this.B.Bb(a,this.J.getVideoData().lengthSeconds)};
g.k.BO=function(){g.Pb(this.D)||LJa(this,this.D);this.F=!1};
g.k.jG=function(a,b){this.C.stop();2===b&&this.vH()};
g.k.hs=function(){if(Z6(this)){this.u.stop();var a=q6(this.wb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.Qe=1;break;case 1082:case 1083:this.B.Qe=0;break;default:this.B.Qe=-1}switch(a.playerState){case 1081:case 1:this.tb(new g.VK(8));this.uH();break;case 1085:case 3:this.tb(new g.VK(9));break;case 1083:case 0:this.tb(new g.VK(2));this.K.stop();this.Bb(this.J.getVideoData().lengthSeconds);break;case 1084:this.tb(new g.VK(4));break;case 2:this.tb(new g.VK(4));this.Bb(l6(a));
break;case -1:this.tb(new g.VK(64));break;case -1E3:this.tb(new g.VK(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=q6(this.wb).u;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,LJa(this,a));a=q6(this.wb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.U.isActive()||this.WH()}else KJa(this)};
g.k.gG=function(){this.J.V("mdxpreviousnextchange")};
g.k.hv=function(){Z6(this)||KJa(this)};
g.k.bG=function(a){isNaN(a)||this.J.V("mdxnowautoplaying",a)};
g.k.BF=function(){this.J.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){Z6(this)&&this.wb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===q6(this.wb).playerState?a7(this,a):b&&this.wb.seekTo(a)};
g.k.WH=function(){var a=this;if(Z6(this)){var b=q6(this.wb);this.events.Jb(this.W);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.W=this.events.P(this.J,"onVolumeChange",function(c){JJa(a,c)})}};
g.k.uH=function(){this.u.stop();if(!this.wb.ma()){var a=q6(this.wb);a.Gb()&&this.tb(new g.VK(8));this.Bb(l6(a));this.u.start()}};
g.k.vH=function(){this.C.stop();this.u.stop();var a=this.wb.C.getReconnectTimeout();2==this.wb.La&&!isNaN(a)&&this.C.start()};
g.k.tb=function(a){this.C.stop();var b=this.I;if(!g.$K(b,a)){var c=g.U(a,2);c!==g.U(this.I,2)&&this.J.Qn(c);this.I=a;NJa(this.B,b,a)}};g.u(b7,g.V);b7.prototype.Ec=function(){this.u.show()};
b7.prototype.jb=function(){this.u.hide()};
b7.prototype.B=function(){g.DK("https://support.google.com/youtube/answer/7640706")};
b7.prototype.C=function(){p4("mdx-manual-pairing-popup-ok");this.jb()};g.u(c7,g.V);c7.prototype.Ec=function(){this.u.show()};
c7.prototype.jb=function(){this.u.hide()};
c7.prototype.B=function(){p4("mdx-privacy-popup-cancel");this.jb()};
c7.prototype.C=function(){p4("mdx-privacy-popup-confirm");this.jb()};g.u(d7,g.V);d7.prototype.B=function(a){MJa(this,a.state)};g.u(e7,g.sR);e7.prototype.F=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.gm=g.Bb(a,this.u,this),g.tR(this,g.Lc(a,this.u)),a=this.J.getOption("remote","currentReceiver"),a=this.u(a),this.options[a]&&this.jh(a),this.enable(!0)):this.enable(!1)};
e7.prototype.u=function(a){return a.key};
e7.prototype.Rh=function(a){return"cast-selector-receiver"===a?"Cast...":this.gm[a].name};
e7.prototype.Ze=function(a){g.sR.prototype.Ze.call(this,a);this.J.setOption("remote","currentReceiver",this.gm[a]);this.Ya.jb()};g.u(f7,g.hO);g.k=f7.prototype;
g.k.create=function(){var a=this.player.S(),b=g.wD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.Q(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.Q(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.Q(a.experiments,"enable_cast_short_lived_lounge_token")};EJa(b,a);this.subscriptions.push(g.Po("yt-remote-before-disconnect",this.LN,this));this.subscriptions.push(g.Po("yt-remote-connection-change",this.sP,this));this.subscriptions.push(g.Po("yt-remote-receiver-availability-change",
this.iG,this));this.subscriptions.push(g.Po("yt-remote-auto-connect",this.qP,this));this.subscriptions.push(g.Po("yt-remote-receiver-resumed",this.pP,this));this.subscriptions.push(g.Po("mdx-privacy-popup-confirm",this.KQ,this));this.subscriptions.push(g.Po("mdx-privacy-popup-cancel",this.JQ,this));this.subscriptions.push(g.Po("mdx-manual-pairing-popup-ok",this.SM,this));this.iG()};
g.k.load=function(){this.player.cancelPlayback();g.hO.prototype.load.call(this);this.rh=new Y6(this,this.player,this.wb);var a=(a=IJa())?a.currentTime:0;var b=V6()?new p6(P6(),void 0):null;0==a&&b&&(a=l6(q6(b)));0!==a&&this.Bb(a);NJa(this,this.Nc,this.Nc);this.player.Rj(6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.vl=this.ji;g.bg(this.rh,this.wb);this.wb=this.rh=null;g.hO.prototype.unload.call(this);this.player.Rj(5);g7(this)};
g.k.ca=function(){g.Qo(this.subscriptions);g.hO.prototype.ca.call(this)};
g.k.Ij=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.rh.iC.apply(this.rh,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Qe};
g.k.TL=function(){return this.loaded?this.rh.suggestion:null};
g.k.rj=function(){return this.wb?q6(this.wb).rj:!1};
g.k.hasNext=function(){return this.wb?q6(this.wb).hasNext:!1};
g.k.Bb=function(a,b){this.UE=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.UE};
g.k.getProgressState=function(){var a=q6(this.wb),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.S().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Oe():!a.isAdPlaying()&&this.player.Oe(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.D+j6(a):a.D,isAtLiveHead:1>=(a.C?a.B+j6(a):a.B)-this.getCurrentTime(),loaded:a.U,seekableEnd:a.C?a.B+j6(a):a.B,seekableStart:0<a.F?a.F+
j6(a):a.F}};
g.k.nextVideo=function(){this.wb&&this.wb.nextVideo()};
g.k.lv=function(){this.wb&&this.wb.lv()};
g.k.LN=function(a){1===a&&(this.Pz=this.wb?q6(this.wb):null)};
g.k.sP=function(){var a=V6()?new p6(P6(),void 0):null;if(a){var b=this.vl;this.loaded&&this.unload();this.wb=a;this.Pz=null;b.key!==this.ji.key&&(this.vl=b,this.load())}else g.ag(this.wb),this.wb=null,this.loaded&&(this.unload(),(a=this.Pz)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,l6(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.iG=function(){var a=[this.ji],b=a.concat,c=FJa();d6()&&g.Eu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.gm=b.call(a,c);a=Q6()||this.ji;h7(this,a);this.player.va("onMdxReceiversChange")};
g.k.qP=function(){var a=Q6();h7(this,a)};
g.k.pP=function(){this.vl=Q6()};
g.k.KQ=function(){this.ls=!0;g7(this);X6=!1;R6&&T6(R6,1);R6=null};
g.k.JQ=function(){this.ls=!1;g7(this);h7(this,this.ji);this.vl=this.ji;X6=!1;R6=null;this.player.playVideo()};
g.k.SM=function(){this.Nu=!0;g7(this);g.Du("yt-remote-manual-pairing-warning-shown",!0,2592E3);X6=!1;R6&&T6(R6,1);R6=null};
g.k.He=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.gm;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?f6():h7(this,b)),this.loaded?this.vl:this.ji;case "quickCast":return 2===this.gm.length&&"cast-selector-receiver"===this.gm[1].key?(b&&f6(),!0):!1}};
g.k.DA=function(){this.wb.DA()};
g.k.Bi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.nO.remote=f7;})(_yt_player);
